### PR TITLE
fix: UPDATE OR REPLACE does not fire FK CASCADE on implicitly-deleted row

### LINKED ISSUE #5537: UPDATE OR REPLACE does not fire FK CASCADE on implicitly-deleted row
## Description
When `UPDATE OR REPLACE` causes an existing row to be implicitly deleted (because the update would violate a UNIQUE constraint), Turso does not fire FK CASCADE actions on the deleted row's children. This leaves orphaned child rows with dangling foreign key references.

## Reproducer
```sql
PRAGMA foreign_keys = ON;

CREATE TABLE parent(id INTEGER PRIMARY KEY, name TEXT UNIQUE);
CREATE TABLE child(id INTEGER PRIMARY KEY, parent_id INT REFERENCES parent(id) ON DELETE CASCADE);

INSERT INTO parent VALUES (10, 'x'), (20, 'y');
INSERT INTO child VALUES (10, 10), (20, 20);

-- REPLACE deletes parent(20) first, then updates parent(10)
UPDATE OR REPLACE parent SET name = 'y' WHERE id = 10;

SELECT * FROM child ORDER BY id;
-- Turso:  10|10 and 20|20  (child 20 survives with dangling FK)
-- SQLite: 10|10             (child 20 correctly cascade-deleted)
```

Per [SQLite documentation](https://sqlite.org/foreignkeys.html): "An ON DELETE CASCADE action means that each row in the child table that was associated with the deleted parent row is also deleted."

The `UPDATE OR REPLACE` code path handles the REPLACE by deleting the conflicting row directly but does not invoke the FK cascade machinery for that implicit deletion.

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by pedrocarlo**
## Motivation and context
Closes #5537

## Description of AI Usage
Generated by Turso Agent

### CODE REVIEW

**Comment by pedrocarlo** [comment]
@claude implement the missing function for foreign key delete actions

**Comment by pedrocarlo** [comment]
@claude rebase with main

**Comment by pedrocarlo** [comment]
I will review this a bit more, but seems decent. Just need to understand and make sure the prepared phase works. I imagine it must be similar to how its done on `Delete` DML.

File: core/translate/fkeys.rs [hunk 1]
```diff
@@ -1627,119 +1627,133 @@ pub struct PreparedFkDeleteAction {
...
-    parent_cursor_id: usize,
-    parent_rowid_reg: usize,
-    database_id: usize,
-) -> Result<Vec<PreparedFkDeleteAction>> {
-    let parent_bt = resolver
-        .with_schema(database_id, |s| s.get_btree_table(parent_table_name))
-        .ok_or_else(|| LimboError::InternalError("parent not btree".into()))?;
-
-    let mut prepared = Vec::new();
+pub struct ForeignKeyActions<T>(Vec<T>);
```
Comment (jussisaurio) [inline core/translate/fkeys.rs:1630]: why do we have this generic?

Comment (pedrocarlo) [reply core/translate/fkeys.rs:1630]: I wanted to try and have a separate `ForeignKeyActions<PreparedUpdateAction>` typestate, but I did not implement it in this PR. If you want I can just make this be `DeleteFKActions`
