### PR TITLE
translate: couple fixes from testing with Gorm

### LINKED ISSUE #3187: panic when creating table with AUTOINCREMENT pk when backticks are used
the following SQL:

```sql
CREATE TABLE `databases` (
`id` integer PRIMARY KEY AUTOINCREMENT,
`created_at` datetime,
`updated_at` datetime,
`deleted_at` datetime,
`hostname` text NOT NULL,
`namespace`,
 `address` text,
`primary_address` text,
CONSTRAINT `uni_databases_hostname` UNIQUE (`hostname`)
);
```
Will panic with the following error:

Image

### PR DESCRIPTION
**Pull request by PThorpe92**
Ongoing tests for [turso-go](https://github.com/tursodatabase/turso-go) have unearthed a couple more issues
closes #3187
### Number 1:
We were getting something like:
```sql
sqlite_autoindex_`databases`_2
```
when creating autoindex for table in Gorm (gorm is notorious for backticks everywhere), because of not normalizing the column name when creating autoindex.

### Number 2:

When creating table with `PRIMARY KEY AUTOINCREMENT`, we were still creating the index, but it wasn't properly handled in    `populate_indices`, because we are doing the following:
```rust
                if column.primary_key && unique_set.is_primary_key {
                    if column.is_rowid_alias {
                        // rowid alias, no index needed
                        continue; // continues, but doesn't consume it..
                    }
```

So if we created such an index entry for the AUTOINCREMENT... we would trip this:
```rust
assert!(automatic_indexes.is_empty(), "all automatic indexes parsed from sqlite_schema should have been consumed, but {} remain", automatic_indexes.len());
```

### CODE REVIEW

File: core/translate/upsert.rs [hunk 1]
```diff
@@ -556,7 +556,7 @@ fn rewrite_upsert_expr_in_place(
                 }
                 // Unqualified column id -> CURRENT
                 Expr::Id(Name::Ident(name)) | Expr::Id(Name::Quoted(name)) => {
-                    if let Some(reg) = col_reg(name.as_str()) {
+                    if let Some(reg) = col_reg(&normalize_ident(name.as_str())) {
```
Comment (TcMits) [inline core/translate/upsert.rs:559]: we only need `normalize_ident` for `Name::Quoted` right?
