### PR TITLE
bindings/rust: propagate the DropBehavior of a dropped tx to next access of DB, instead of panicing

### LINKED ISSUE #3748: Rust bindings will panic if any client error happens during interactive tx
```rust
    #[tokio::test]
    async fn test_panic_on_application_error() -> Result<()> {
        let mut conn = checked_memory_handle().await.unwrap();
        let tx = conn.transaction().await?;
        tx.execute("INSERT INTO foo VALUES(?)", &[1]).await?;
        
        // Simulate an application error that causes early return
        // without calling commit(), rollback(), or finish()
        if true {
            return Err(Error::SqlExecutionFailure("End user screwed something up".to_string()));
        }
        
        // This line is never reached, so finish() is never called
        tx.finish().await?;
        Ok(())
    }
```

```rust
failures:

---- transaction::test::test_panic_on_application_error stdout ----

thread 'transaction::test::test_panic_on_application_error' panicked at bindings/rust/src/transaction.rs:190:13:
Transaction dropped without finish()
```

### PR DESCRIPTION
**Pull request by jussisaurio**
Closes #3748

Right now if any error happens during an interactive tx that causes the `Transaction` to drop, the program will panic.

To prevent this, we store the `DropBehavior` of the transaction on the `Connection` when it drops and issue the corresponding action (ROLLBACK / COMMIT / IGNORE / PANIC) the next time `Connection` is used to access the database. This defaults to `IGNORE`.

I don't know how good this solution is, but we can at least prevent a panic by storing whether the connection has a dangling transaction and roll it back automatically the next time the connection tries to do something.

### CODE REVIEW

File: bindings/rust/src/transaction.rs [hunk 1]
```diff
@@ -186,8 +186,10 @@ impl Deref for Transaction<'_> {
 impl Drop for Transaction<'_> {
     #[inline]
     fn drop(&mut self) {
-        if self.must_finish {
-            panic!("Transaction dropped without finish()")
+        if self.in_progress {
+            self.conn.dangling_tx.store(true, Ordering::SeqCst);
+        } else {
+            self.conn.dangling_tx.store(false, Ordering::SeqCst);
```
Comment (PThorpe92) [inline bindings/rust/src/transaction.rs]: nit
```rust
           self.conn.dangling_tx.store(self.in_progress, Ordering::SeqCst);
```
