### PR TITLE
Enforce NOT NULL when updating virtual columns

### LINKED ISSUE #6159: NOT NULL on virtual generated column not enforced on UPDATE
## Description

When a virtual generated column has a NOT NULL constraint, INSERT correctly rejects NULL values. However, UPDATE allows changing the base column to produce a NULL generated value without raising a constraint error.

## Reproducer

```sql
CREATE TABLE t1(a INTEGER, b GENERATED ALWAYS AS (a*2) VIRTUAL NOT NULL);
INSERT INTO t1(a) VALUES(1),(2),(3);

-- BUG: UPDATE allows NULL, violating NOT NULL on gen col
UPDATE t1 SET a = NULL WHERE a = 2;
SELECT * FROM t1;
-- Turso: 1|2 / |  / 3|6 (row becomes NULL, NULL)
-- SQLite: NOT NULL constraint failed: t1.b

-- OK: INSERT correctly rejects NULL
INSERT INTO t1(a) VALUES(NULL);
-- Both: NOT NULL constraint failed: t1.b
```

Per [SQLite documentation](https://sqlite.org/gencol.html): "Generated columns may have NOT NULL, CHECK, and UNIQUE constraints, and foreign key constraints, just like ordinary columns."

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by LeMikaelF**
## Description

* Enforce NOT NULL when updating virtual columns
* Some refactoring to help with readability
* Add missing tests for existing code (spotted this while I was working)

Closes #6159

### CODE REVIEW

File: core/translate/emitter/update.rs [hunk 1]
```diff
@@ -483,116 +508,128 @@ fn emit_update_column_values<'a>(
...
-                    // comment on NoConstantOptReason::CustomTypeEncode.
-                    let has_custom_encode = {
-                        let ty = &table_column.ty_str;
-                        !ty.is_empty()
-                            && t_ctx
-                                .resolver
-                                .schema
-                                .get_type_def_unchecked(ty)
-                                .is_some_and(|td| td.encode.is_some())
+                    let self_table_context = match table_column.generated_type() {
```
Comment (LeMikaelF) [inline core/translate/emitter/update.rs:518]: I didn't change the code, I just wrapped the whole branch with `program.with_self_table_context` and git doesn't understand the change.

File: core/translate/emitter/update.rs [hunk 2]
```diff
@@ -868,23 +905,18 @@ fn emit_update_insns<'a>(
...
     };
 
-    let rowid_set_clause_reg = if has_user_provided_rowid {
+    let rowid_set_clause_reg = if updates_rowid {
         Some(program.alloc_register())
     } else {
         None
     };
 
-    turso_assert!(
```
Comment (LeMikaelF) [inline core/translate/emitter/update.rs:883]: all this assertion checked was the block just above it, so I removed it

File: core/translate/emitter/update.rs
Comment (LeMikaelF) [inline core/translate/emitter/update.rs:1039]: over 20 arguments 😕 somewhere in here, there's an abstraction waiting to be born

**Review by pereman2 — APPROVED** [review]

**Review by jussisaurio — APPROVED** [review]
