### PR TITLE
Cte fixes

### LINKED ISSUE #4647: CTEs don't support compound selects

### LINKED ISSUE #4648: CTEs cannot be used together with a DML statement
e.g. `WITH c AS (SELECT...) INSERT...`

### PR DESCRIPTION
**Pull request by jussisaurio**
- Support compound selects in CTE
- Support CTEs before a DML statement
- Support referring to CTEs in WHERE clause subqueries
- Support CTEs preceding a SELECT without a FROM clause: `WITH c AS (...) SELECT (SELECT * from c)`
- Fix wrong column names in compound select inside CTE: use leftmost subselect's column names

Closes #4647
Closes #4648

Diff is mainly tests.

AI usage: all code generated with claude code, many iterations of 1. write plan 2. implement 3. have subagent review the implementation 4. address comments. after each iteration i closed claude code and asked another agent to continue, i.e. manual ralphwigguming

### CODE REVIEW

File: core/translate/optimizer/mod.rs [hunk 1]
```diff
@@ -755,7 +350,21 @@ fn add_ephemeral_table_to_update_plan(
...
+                Plan::Select(select_plan) => optimize_select_plan(select_plan, schema)?,
+                Plan::CompoundSelect {
+                    left, right_most, ..
+                } => {
+                    optimize_select_plan(right_most, schema)?;
+                    for (select_plan, _) in left {
+                        optimize_select_plan(select_plan, schema)?;
+                    }
+                }
+                Plan::Delete(_) | Plan::Update(_) => {
```
Comment (PThorpe92) [inline core/translate/optimizer/mod.rs:364]: assertion here?

File: core/translate/insert.rs [hunk 2]
```diff
@@ -216,12 +212,31 @@ pub fn translate_insert(
...
+                Some(select_with) => {
+                    // Prepend INSERT's CTEs to SELECT's CTEs
+                    let mut merged = insert_with.ctes;
+                    merged.append(&mut select_with.ctes);
+                    select_with.ctes = merged;
+                    select_with.recursive |= insert_with.recursive;
+                }
+                None => select.with = Some(insert_with),
+            }
+        } else {
```
Comment (PThorpe92) [inline core/translate/insert.rs:228]: unneeded else block.

EDIT: hmm actually not sure if this is correct? looking into this rn

File: core/translate/select.rs [hunk 3]
```diff
@@ -705,6 +705,23 @@ fn replace_column_number_with_copy_of_column_expr(
     Ok(())
 }
 
+/// Count required cursors for a Plan (either Select or CompoundSelect)
+fn count_plan_required_cursors_for_plan(plan: &Plan) -> usize {
```
Comment (PThorpe92) [inline core/translate/select.rs]: `count_required_cursors_for_plan`
```suggestion
fn count_required_cursors_for_plan(plan: &Plan) -> usize {
```

File: core/translate/insert.rs (hunk 2 above)
Comment (jussisaurio) [reply core/translate/insert.rs:228]: it is correct

```sql
sqlite> create table t(x); create table u(x);
sqlite> with unused as (select * from t) insert into u values (666);
sqlite> with unused as (select * from t) insert into u default values;
```

Also I think this `else` block actually serves as fairly decent documentation

Comment (jussisaurio) [reply core/translate/insert.rs:228]: the merging part is sth like

```sql
sqlite> with weird as (select * from t) insert into u with ref_weird as (select * from weird) select * from ref_weird;
```

Comment (jussisaurio) [reply core/translate/insert.rs:228]: same stuff on this branch:

```sql
turso> create table t(x); create table u(x);
turso> with unused as (select * from t) insert into u values (666);
turso> select * from t;
turso> select * from u;
┌─────┐
│ x   │
├─────┤
│ 666 │
└─────┘
turso> insert into t values ('t_value');
turso> with weird as (select * from t) insert into u with ref_weird as (select * from weird) select * from ref_weird;
turso> select * from u;
┌─────────┐
│ x       │
├─────────┤
│     666 │
├─────────┤
│ t_value │
└─────────┘
turso> 
```

File: core/translate/optimizer/mod.rs (hunk 1 above)
Comment (jussisaurio) [reply core/translate/optimizer/mod.rs:364]: yeah this is slop, sorry - will add error here

File: core/translate/insert.rs (hunk 2 above)
Comment (jussisaurio) [reply core/translate/insert.rs:228]: Changed the wording to:

```rust
        } else {
            // WITH clause on INSERT with VALUES or DEFAULT VALUES is not useful
            // e.g. WITH unused AS (SELECT c FROM a) INSERT INTO b VALUES (1, 2, 3)
            // but: we can, and indeed must, just ignore it instead of erroring.
            // leaving this empty else block here for documentation.
        }
```

File: core/translate/optimizer/mod.rs (hunk 1 above)
Comment (jussisaurio) [reply core/translate/optimizer/mod.rs:364]:
```rust
                Plan::Delete(_) | Plan::Update(_) => {
                    return Err(LimboError::InternalError(
                        "DELETE/UPDATE plans should not appear in FROM clause subqueries"
                            .to_string(),
                    ));
                }
```

File: core/translate/select.rs (hunk 3 above)
Comment (jussisaurio) [reply core/translate/select.rs]: Renamed a bunch of these because they had stupid names 3f7909e3e4ed25fe23de385784afa5aa3ecf955b
