### PR TITLE
Fix wal truncate on shutdown even after restart

### LINKED ISSUE #2492: bug: checkpoint always writes something even if there is no new writes
This is my current state: 

```
ls

.rw-r--r--@  25k avi  7 Aug 18:04 database.db
.rw-r--r--@  21k avi  7 Aug 18:04 database.db-wal
```

then I did a read:
```
cargo run -- database.db

select * from t;
```

then I did `Cmd+D` and I see these logs: 

```
2025-08-07T12:35:40.737534Z DEBUG ThreadId(01) sync: turso_core::storage::wal: 1129: wal_sync
2025-08-07T12:35:40.737788Z TRACE ThreadId(01) sync:sync: turso_core::io::unix: 603: fsync
2025-08-07T12:35:40.737900Z DEBUG ThreadId(01) sync:sync: turso_core::storage::wal: 1133: wal_sync finish
2025-08-07T12:35:40.738384Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=Start
2025-08-07T12:35:40.738477Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 178: write_lock(true)
2025-08-07T12:35:40.738510Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 178: write_lock(true)
2025-08-07T12:35:40.738539Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1397: checkpoint_start(min_frame=1, max_frame=5)
2025-08-07T12:35:40.738589Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=ReadFrame
2025-08-07T12:35:40.738641Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1432: checkpoint page(state=ReadFrame, page=3, frame=5)
2025-08-07T12:35:40.738670Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::wal: 900: read_frame(5)
2025-08-07T12:35:40.738704Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::sqlite3_ondisk: 1717: begin_read_wal_frame(offset=16536)
2025-08-07T12:35:40.738752Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread: turso_core::io::unix: 497: pread n: 4096
2025-08-07T12:35:40.738778Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread:finish_read_page: turso_core::storage::sqlite3_ondisk: 808: page_idx=3
2025-08-07T12:35:40.738823Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=WaitReadFrame
2025-08-07T12:35:40.738834Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=AccumulatePage
2025-08-07T12:35:40.738845Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 189: set_dirty(page=3)
2025-08-07T12:35:40.739150Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=ReadFrame
2025-08-07T12:35:40.739166Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1432: checkpoint page(state=ReadFrame, page=3, frame=5)
2025-08-07T12:35:40.739180Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::wal: 900: read_frame(5)
2025-08-07T12:35:40.739192Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::sqlite3_ondisk: 1717: begin_read_wal_frame(offset=16536)
2025-08-07T12:35:40.739210Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread: turso_core::io::unix: 497: pread n: 4096
2025-08-07T12:35:40.739231Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread:finish_read_page: turso_core::storage::sqlite3_ondisk: 808: page_idx=3
2025-08-07T12:35:40.739258Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=WaitReadFrame
2025-08-07T12:35:40.739269Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=AccumulatePage
2025-08-07T12:35:40.739278Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 189: set_dirty(page=3)
2025-08-07T12:35:40.739372Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=ReadFrame
2025-08-07T12:35:40.739384Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1432: checkpoint page(state=ReadFrame, page=3, frame=5)
2025-08-07T12:35:40.739397Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::wal: 900: read_frame(5)
2025-08-07T12:35:40.739409Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::sqlite3_ondisk: 1717: begin_read_wal_frame(offset=16536)
2025-08-07T12:35:40.739430Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread: turso_core::io::unix: 497: pread n: 4096
2025-08-07T12:35:40.739456Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread:finish_read_page: turso_core::storage::sqlite3_ondisk: 808: page_idx=3
2025-08-07T12:35:40.739483Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=WaitReadFrame
2025-08-07T12:35:40.739493Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=AccumulatePage
2025-08-07T12:35:40.739501Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 189: set_dirty(page=3)
2025-08-07T12:35:40.739511Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=ReadFrame
2025-08-07T12:35:40.739522Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1432: checkpoint page(state=ReadFrame, page=3, frame=5)
2025-08-07T12:35:40.739533Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::wal: 900: read_frame(5)
2025-08-07T12:35:40.739544Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::sqlite3_ondisk: 1717: begin_read_wal_frame(offset=16536)
2025-08-07T12:35:40.739559Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread: turso_core::io::unix: 497: pread n: 4096
2025-08-07T12:35:40.739578Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread:finish_read_page: turso_core::storage::sqlite3_ondisk: 808: page_idx=3
2025-08-07T12:35:40.739602Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=WaitReadFrame
2025-08-07T12:35:40.739610Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=AccumulatePage
2025-08-07T12:35:40.739619Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 189: set_dirty(page=3)
2025-08-07T12:35:40.739628Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=ReadFrame
2025-08-07T12:35:40.739638Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1432: checkpoint page(state=ReadFrame, page=3, frame=5)
2025-08-07T12:35:40.739649Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::wal: 900: read_frame(5)
2025-08-07T12:35:40.739659Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame: turso_core::storage::sqlite3_ondisk: 1717: begin_read_wal_frame(offset=16536)
2025-08-07T12:35:40.739674Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread: turso_core::io::unix: 497: pread n: 4096
2025-08-07T12:35:40.739692Z TRACE ThreadId(01) wal_checkpoint:checkpoint:read_frame:pread:finish_read_page: turso_core::storage::sqlite3_ondisk: 808: page_idx=3
2025-08-07T12:35:40.739715Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=WaitReadFrame
2025-08-07T12:35:40.739724Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=AccumulatePage
2025-08-07T12:35:40.739732Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 189: set_dirty(page=3)
2025-08-07T12:35:40.739741Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=FlushBatch
2025-08-07T12:35:40.739753Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1484: started checkpoint backfilling batch
2025-08-07T12:35:40.739782Z  INFO ThreadId(01) wal_checkpoint:checkpoint:write_pages_vectored: turso_core::storage::database: 100: Writing pages 3 to database file
2025-08-07T12:35:40.739844Z TRACE ThreadId(01) wal_checkpoint:checkpoint:write_pages_vectored:pwritev:pwrite: turso_core::io::unix: 526: pwrite n: 4096
2025-08-07T12:35:40.739871Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:write_pages_vectored: turso_core::storage::sqlite3_ondisk: 965: write_pages_vectored: 1 pages to write, runs: 1
2025-08-07T12:35:40.739885Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=WaitFlush
2025-08-07T12:35:40.739897Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1497: checkpoint backfilling batch done
2025-08-07T12:35:40.739905Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1502: finished checkpoint backfilling batch
2025-08-07T12:35:40.739917Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 1144: read_page(page_idx = 3)
2025-08-07T12:35:40.739937Z TRACE ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::page_cache: 162: cache_get(key=PageCacheKey { pgno: 3 })
2025-08-07T12:35:40.739958Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 194: clear_dirty(page=3)
2025-08-07T12:35:40.739966Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=ReadFrame
2025-08-07T12:35:40.739977Z  INFO ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1417: checkpoint done, no more pages to checkpoint
2025-08-07T12:35:40.739985Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::wal: 1373: state=Done
2025-08-07T12:35:40.739997Z DEBUG ThreadId(01) wal_checkpoint:checkpoint: turso_core::storage::pager: 194: clear_dirty(page=3)
2025-08-07T12:35:40.740015Z TRACE ThreadId(01) wal_checkpoint: turso_core::storage::pager: 39: state=Start
2025-08-07T12:35:40.740036Z TRACE ThreadId(01) wal_checkpoint:read_page: turso_core::storage::pager: 1092: read_page(page_idx = 1)
2025-08-07T12:35:40.740045Z TRACE ThreadId(01) wal_checkpoint:read_page: turso_core::storage::page_cache: 162: cache_get(key=PageCacheKey { pgno: 1 })
2025-08-07T12:35:40.740053Z TRACE ThreadId(01) wal_checkpoint:read_page: turso_core::storage::pager: 1096: read_page(page_idx = 1) = cached
2025-08-07T12:35:40.740075Z TRACE ThreadId(01) wal_checkpoint: turso_core::storage::pager: 39: state=CreateHeader { page: Page { inner: UnsafeCell { .. } } }
2025-08-07T12:35:40.740111Z TRACE ThreadId(01) wal_checkpoint: turso_core::storage::wal: 185: unlock(value=2)
2025-08-07T12:35:40.740121Z TRACE ThreadId(01) wal_checkpoint: turso_core::storage::wal: 185: unlock(value=2)
2025-08-07T12:35:40.740132Z DEBUG ThreadId(01) wal_checkpoint: turso_core::storage::pager: 207: clear loaded 1
2025-08-07T12:35:40.740139Z DEBUG ThreadId(01) wal_checkpoint: turso_core::storage::page_cache: 207: clean(page=1)
2025-08-07T12:35:40.740148Z DEBUG ThreadId(01) wal_checkpoint: turso_core::storage::pager: 207: clear loaded 3
2025-08-07T12:35:40.740154Z DEBUG ThreadId(01) wal_checkpoint: turso_core::storage::page_cache: 207: clean(page=3)
```

I don't see the WAL file being truncated either: 

```
.rw-r--r--@  25k avi  7 Aug 18:10 database.db
.rw-r--r--@  21k avi  7 Aug 18:04 database.db-wal
```

btw there is no need to do any reads either. Just open the DB and close it, you will see these logs. You will see some writes being done

What I am expecting: checkpointing writes all the pages the first time and not keep writing everytime: 

```
2025-08-07T12:40:25.106707Z  INFO ThreadId(01) wal_checkpoint:checkpoint:write_pages_vectored: turso_core::storage::database: 100: Writing pages 3 to database file
2025-08-07T12:40:25.106776Z TRACE ThreadId(01) wal_checkpoint:checkpoint:write_pages_vectored:pwritev:pwrite: turso_core::io::unix: 526: pwrite n: 4096
2025-08-07T12:40:25.106802Z DEBUG ThreadId(01) wal_checkpoint:checkpoint:write_pages_vectored: turso_core::storage::sqlite3_ondisk: 965: write_pages_vectored: 1 pages to write, runs: 1
```

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Description

Ensure TRUNCATE checkpoint clears stale WAL bytes after a RESTART/log reset (wal_max_frame=0), preventing repeated backfill on reopen. Add regression test to cover shutdown truncation after restart.

## Motivation and context

When the WAL is restarted, wal_max_frame is reset to 0 but the WAL file may still contain old frames. Shutdown TRUNCATE skipped truncation in that case, leaving stale WAL bytes and causing re-checkpointing on each open. This change makes TRUNCATE clear the file whenever all frames are backfilled, matching expected shutdown behavior.

Closes #2492

### CODE REVIEW

File: core/storage/wal.rs [hunk 1]
```diff
@@ -89,7 +89,9 @@ impl CheckpointResult {
         self.wal_max_frame == self.wal_total_backfilled
     }
     pub fn should_truncate(&self) -> bool {
-        self.everything_backfilled() && self.wal_max_frame > 0
+        // TRUNCATE should also clear any stale WAL bytes when the log was restarted
+        // (wal_max_frame=0) but the file still contains old frames.
```
Comment (avinassh) [inline core/storage/wal.rs:93]: may be we should assert this

Comment (kumarUjjawal) [reply core/storage/wal.rs:93]: isn't should_truncate() a policy decision. It’s not asserting a runtime invariant. We also don’t have evidence at this point that the WAL file actually contains stale frames. so we can't add assert
