### PR TITLE
fix/mvcc: set log offset to end of file after recovery finishes

### LINKED ISSUE #3495: mvcc: logical log doesnt move its offset to the end properly after recovery and overwrites existing entries

### PR DESCRIPTION
**Pull request by jussisaurio**
otherwise we start overwriting existing log entries

Closes #3495

### CODE REVIEW

File: core/mvcc/persistent_storage/logical_log.rs [hunk 1]
```diff
@@ -231,7 +231,7 @@ enum StreamingState {
 pub struct StreamingLogicalLogReader {
     file: Arc<dyn File>,
     /// Offset to read from file
-    offset: usize,
```
Comment (sivukhin) [inline core/mvcc/persistent_storage/logical_log.rs:234]: NIT: why not `u64`?

**Review by sivukhin — APPROVED** [review]

File: core/mvcc/persistent_storage/logical_log.rs (hunk 1 above)
Comment (jussisaurio) [reply core/mvcc/persistent_storage/logical_log.rs:234]: simply because it already was `usize` - no practical reason

Comment (sivukhin) [reply core/mvcc/persistent_storage/logical_log.rs:234]: Ok, sure. I just have flashbacks from making changes in the WAL code where you have a wild mix of usize, u64 and u32 :)

I think we can safely use u64 almost everywhere and be happy.

Comment (jussisaurio) [reply core/mvcc/persistent_storage/logical_log.rs:234]: Yeah - I will not change it in this PR because it would cascade into either a lot of casts elsewhere or a lot of "change _ to u64" diffs elsewhere. We can do a sweeping "use u64" refactor at some point.
