### PR TITLE
core/mvcc: check integer primary key conflicts

### LINKED ISSUE #3588: MVCC doesn't enforce rowid uniqueness constraints
This test succeeds:

```rust
#[test]
fn test_mvcc_same_primary_key() {
    let tmp_db = TempDatabase::new_with_opts("test_mvcc_same_primary_key.db", turso_core::DatabaseOpts::new().with_mvcc(true));
    let conn = tmp_db.connect_limbo();

    // Create table
    execute_and_log(&conn, "CREATE TABLE test (id INTEGER PRIMARY KEY)").unwrap();

    // First transaction
    execute_and_log(&conn, "BEGIN CONCURRENT").unwrap();
    execute_and_log(&conn, "INSERT INTO test VALUES (666)").unwrap();
    execute_and_log(&conn, "COMMIT").unwrap();

    // Second transaction with same primary key
    execute_and_log(&conn, "BEGIN CONCURRENT").unwrap();
    execute_and_log(&conn, "INSERT INTO test VALUES (666)").unwrap();
    execute_and_log(&conn, "COMMIT").unwrap();

    // This should've already failed at this point, but let's try to query it anyway
    let stmt = query_and_log(&conn, "SELECT * FROM test ORDER BY id").unwrap().unwrap();
    let rows = helper_read_all_rows(stmt);

    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0][0], Value::Integer(666));
}
```

### PR DESCRIPTION
**Pull request by pereman2**
## Description

When inserting a new version to a table we need to check there is no rowid conflicts. With this PR we will check if there is any visible version with same rowid OR there is another row version being inserted with same rowid.

Fixes #3588 
## Description of AI Usage

none

### CODE REVIEW

**Comment by jussisaurio** [comment]
Just to be clear do we catch rowid conflicts from btree even before this change?

**Comment by pereman2** [comment]
> Just to be clear do we catch rowid conflicts from btree even before this change?

right now, since we don't concurrently checkpoint, btree is check through regular byte code in case it is needed through `NotExists` if I'm not wrong. I wanted to keep this simple for now.

File: core/mvcc/database/mod.rs [hunk 1]
```diff
@@ -816,11 +828,90 @@ impl<Clock: LogicalClock> StateTransition for CommitStateMachine<Clock> {
...
+                                    }
+                                }
+                            }
+                            Some(TxTimestampOrID::Timestamp(begin_ts)) => {
+                                // Committed version - check if it was inserted after we started
+                                if begin_ts >= tx.begin_ts {
+                                    // Duplicate! A version was committed after we started
+                                    return Err(LimboError::WriteWriteConflict);
+                                }
+                                // Commited before we started, any other previous versions are also committed before us so irrelevant.
```
Comment (jussisaurio) [inline core/mvcc/database/mod.rs]: I don't get this part. Why isn't a previously committed version that has the same row id a conflict?

Comment (jussisaurio) [reply core/mvcc/database/mod.rs]: If we mean this should've been caught beforehand then this should be an assert

Comment (pereman2) [reply core/mvcc/database/mod.rs]: Aha true! I changed it so that it asserts instead of breaking good catch
