### PR TITLE
fix(json): return unquoted strings as plain SQL text

### LINKED ISSUE #5753: JSON_GROUP_ARRAY fails with "malformed JSON" for text from JSON_EXTRACT
## Description
`JSON_GROUP_ARRAY()` fails with "malformed JSON" when the input is a text value extracted via `JSON_EXTRACT()` or `->>`. Integer values and the `->` operator work fine.

## Reproducer
```sql
CREATE TABLE config(id INTEGER PRIMARY KEY, data TEXT);
INSERT INTO config VALUES (1, '{"name":"Alice","age":30}');
INSERT INTO config VALUES (2, '{"name":"Bob","age":25}');

SELECT JSON_GROUP_ARRAY(JSON_EXTRACT(data, '$.name')) FROM config;
-- Turso: Parse error: malformed JSON
-- SQLite: ["Alice","Bob"]

SELECT JSON_GROUP_ARRAY(data ->> '$.name') FROM config;
-- Turso: Parse error: malformed JSON
-- SQLite: ["Alice","Bob"]

-- Integer values work fine:
SELECT JSON_GROUP_ARRAY(JSON_EXTRACT(data, '$.age')) FROM config;
-- Both: [30,25]

-- The -> operator (returns JSON fragment) works:
SELECT JSON_GROUP_ARRAY(data -> '$.name') FROM config;
-- Both: ["Alice","Bob"]
```

`JSON_EXTRACT`/`->>` returns unquoted text (e.g., `Alice` not `"Alice"`), which is not valid JSON. The aggregate function sees a JSON subtype flag and tries to parse it, failing on bare text.

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by naivcit**
JSON_EXTRACT and ->> incorrectly preserved the JSON subtype flag on unquoted text, causing subsequent JSON functions to fail when parsing bare text. This change ensures they are returned as plain strings.

Fixes #5753

### CODE REVIEW

File: core/json/mod.rs [hunk 1]
```diff
@@ -1231,6 +1232,20 @@ mod tests {
...
+        let extracted_name =
+            json_extract(data, &[Value::build_text("$.name")], &json_cache).unwrap();
+        let result = json_array(&[extracted_name]).unwrap();
+        if let Value::Text(res) = result {
+            assert_eq!(res.as_str(), "[\"Alice\"]");
+        } else {
+            panic!("Expected Text");
+        }
+    }
+
```
Comment (LeMikaelF) [inline core/json/mod.rs]: this is redundant with the sqltest tests
```suggestion
```

File: core/json/mod.rs [hunk 2]
```diff
@@ -597,7 +597,8 @@ pub fn json_string_to_db_type(
             if matches!(flag, OutputVariant::ElementType) {
                 json_string.remove(json_string.len() - 1);
                 json_string.remove(0);
-                Ok(Value::Text(Text::json(json_string)))
+                // Unquoted text is not a valid JSON fragment
```
Comment (LeMikaelF) [inline core/json/mod.rs]:
```suggestion
```

**Comment by naivcit** [comment]
@LeMikaelF thanks for the review and pushing review suggestions . I see currently 1 workflow is failing but that seems due to some unrelated network error 
   `error sending request for url (https://productionresultssa14.blob.core.windows.net/actions-cache/3dd-3191683958?se=2026-03-11T02%3A39%3A51Z&sig=FtilCAbgomd7%2FDJFrMJ8XczQnKaSSTzgB%2Bu%2BzUrHo7c%3D&ske=2026-03-11T05%3A55%3A15Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2026-03-11T01%3A55%3A15Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2026-03-11T02%3A29%3A46Z&sv=2025-11-05`
