### PR TITLE
translate: disallow creating/dropping internal tables

### LINKED ISSUE #3313: It should not be possible to create or drop a table with the sqlite_ prefix
From the SQLITE [documentation](https://www.sqlite.org/lang_createtable.html#the_create_table_command):

>  Table names that begin with "sqlite_" are reserved for internal use. It is an error to attempt to create a table with a name that starts with "sqlite_". 

But Turso doesn't block this. It even gives a scary message (but does nothing) if the user tries to drop `sqlite_schema`:

```
turso> drop table sqlite_schema;
  × Corrupt database: Invalid page number 1 for free operation
```

You can even screw up a database by deleting the `sqlite_sequence` when it is in use, and then SQLite can't insert into the affected tables anymore, saying the database is malformed:

```
rust/limbo main % sqlite3 /tmp/mydb
SQLite version 3.50.4 2025-07-30 19:33:53
Enter ".help" for usage hints.
sqlite> create table t(a integer primary key autoincrement);
sqlite> insert into t default values;
sqlite> 

rust/limbo main % ./target/debug/tursodb /tmp/mydb
Turso v0.2.0-pre.8
Enter ".help" for usage hints.
This software is ALPHA, only use for development, testing, and experimentation.
turso> drop table sqlite_sequence;
turso> 
rust/limbo main % sqlite3 /tmp/mydb               
SQLite version 3.50.4 2025-07-30 19:33:53
Enter ".help" for usage hints.
sqlite> select * from t;
1
sqlite> insert into t default values;
Parse error: database disk image is malformed (11)
```

### PR DESCRIPTION
**Pull request by jussisaurio**
edit: we can't disallow 'turso_' prefix though, because turso-sync-engine uses it

Closes #3313

### CODE REVIEW

**Comment by jussisaurio** [comment]
i guess we can't prevent `turso_` prefix because turso-sync-engine uses it

File: core/translate/index.rs [hunk 1]
```diff
@@ -42,7 +42,17 @@ pub fn translate_create_index(
             "CREATE INDEX is disabled by default. Run with `--experimental-indexes` to enable this feature."
         );
     }
-    let idx_name = normalize_ident(idx_name);
+    let idx_name = normalize_ident(original_idx_name);
+
+    if RESERVED_TABLE_PREFIXES
+        .iter()
+        .any(|prefix| idx_name.starts_with(prefix))
```
Comment (sivukhin) [inline core/translate/index.rs:54]: Why we compare index name and not table name?

**Comment by penberg** [comment]
@jussisaurio This has some conflicts.
