### PR TITLE
Fix external sorter losing rows when chunks need async IO

### LINKED ISSUE #4033: "wrong # of entries" in simulator
From commit https://github.com/tursodatabase/turso/commit/fb31fd56ba5ea77f280e004d2b323105705b6d5c

```sh
./scripts/run-sim --maximum-tests 1000 --min-tick 10 --max-tick 50 --profile write_heavy --seed 15590731512610634011 loop -n 10 -s
```

gives:

```
Error: failed with error: 'InternalError("simulation failed: - wrong # of entries in index idx_brave_lombroso_118_lustrous\n- row 1 missing from index idx_brave_lombroso_118_lustrous\n- row 2 missing from index idx_brave_lombroso_118_lustrous\n- row 3 missing from index idx_brave_lombroso_118_lustrous\n- row 4 missing from index idx_brave_lombroso_118_lustrous\n- row 5 missing from index idx_brave_lombroso_118_lustrous\n- row 6 missing from index idx_brave_lombroso_118_lustrous\n- row 10 missing from index idx_brave_lombroso_118_lustrous\n- row 12 missing from index idx_brave_lombroso_118_lustrous\n- row 17 missing from index idx_brave_lombroso_118_lustrous\n- row 18 missing from index idx_brave_lombroso_118_lustrous\n- row 19 missing from index idx_brave_lombroso_118_lustrous\n- row 20 missing from index idx_brave_lombroso_118_lustrous\n- row 21 missing from index idx_brave_lombroso_118_lustrous\n- row 22 missing from index idx_brave_lombroso_118_lustrous\

...
```

See https://github.com/tursodatabase/turso/runs/56168361944

### LINKED ISSUE #4125: Simulator assertion failure: "ERROR limbo_sim: 239: simulation failed: 'Corrupt("Incomplete record")'"
## Simulator failure type:assertion
 
 - **Seed**: 2213714407091978685
 - **Git Hash**: a06e2cc8e63347fbfa595fbf44628fc06bd2dd2b
 - **Command**: `limbo-sim --seed 2213714407091978685 --disable-bugbase --profile faultless --memory-io --differential --minimum-tests 100 --maximum-tests 1000 loop -n 10 --short-circuit`
 - **Timestamp**: 2025-12-08T00:21:04.510Z

 ### Run locally with Docker

 ```
 git checkout a06e2cc8e63347fbfa595fbf44628fc06bd2dd2b
 docker buildx build -t limbo-sim:a06e2cc -f simulator-docker-runner/Dockerfile.simulator . --build-arg GIT_HASH=$(git rev-parse HEAD)
 docker run --network host limbo-sim:a06e2cc --seed 2213714407091978685 --disable-bugbase --profile faultless --memory-io --differential --minimum-tests 100 --maximum-tests 1000 loop -n 10 --short-circuit
 ```

 ### Output
 
 ```
 ERROR limbo_sim: 239: simulation failed: 'Corrupt("Incomplete record")'
 INFO limbo_sim: 251: Starting to shrink
 INFO limbo_sim::shrink::plan: 92: Shrinking interaction plan from 532 to 67 interactions
 INFO limbo_sim: 254: Read: 110, Insert: 22, Delete: 18, Update: 13, Create: 16, CreateIndex: 2, Drop: 0, Begin: 8, Commit: 5, Rollback: 3, Alter Table: 0, Drop Index: 1
 INFO limbo_sim::runner::differential: 26: Executing database interaction plan...
 INFO execute_interaction_turso{conn_index=0 interaction=CREATE TABLE shimmering_jin_0 (passionate_meydan_1 TEXT, vivacious_blat_2 REAL, fantastic_cusicanqui_3 TEXT, relaxed_bowlegs_4 TEXT, polite_kay_5 INTEGER, ample_weinstein_6 BLOB, charming_dragon_7 REAL, upbeat_critchley_8 BLOB, open_minded_punkerslut_9 BLOB, knowledgeable_radioazionecroatia_10 TEXT); -- 0}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=0 interaction=CREATE TABLE shimmering_jin_0 (passionate_meydan_1 TEXT, vivacious_blat_2 REAL, fantastic_cusicanqui_3 TEXT, relaxed_bowlegs_4 TEXT, polite_kay_5 INTEGER, ample_weinstein_6 BLOB, charming_dragon_7 REAL, upbeat_critchley_8 BLOB, open_minded_punkerslut_9 BLOB, knowledgeable_radioazionecroatia_10 TEXT); -- 0}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=-- ASSUME table shimmering_jin_0 exists; -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=-- ASSUME table shimmering_jin_0 exists; -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=INSERT INTO shimmering_jin_0 VALUES ('captivating_man', -5295242834.115741, 'faithful_oberhaus', 'breathtaking_manifold', -212271000441473798, X'736C65656B5F6265726E737465696E', 1384678192.206667, X'656E676167696E675F6E65677261', X'73706563746163756C61725F63617A617261626574', 'patient_poznan'), ('fearless_bombas', -5817786983.247339, 'awesome_khayati', 'devoted_george', 1194042421446631165, X'72656C617865645F7A696C656C69', 5398476000.087622, X'666169746866756C5F6D696E7969', X'73696E636572655F6275726E73', 'affectionate_bacca'); -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=INSERT INTO shimmering_jin_0 VALUES ('captivating_man', -5295242834.115741, 'faithful_oberhaus', 'breathtaking_manifold', -212271000441473798, X'736C65656B5F6265726E737465696E', 1384678192.206667, X'656E676167696E675F6E65677261', X'73706563746163756C61725F63617A617261626574', 'patient_poznan'), ('fearless_bombas', -5817786983.247339, 'awesome_khayati', 'devoted_george', 1194042421446631165, X'72656C617865645F7A696C656C69', 5398476000.087622, X'666169746866756C5F6D696E7969', X'73696E636572655F6275726E73', 'affectionate_bacca'); -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=SELECT * FROM shimmering_jin_0 WHERE (((shimmering_jin_0.passionate_meydan_1 != 'relaxed_kamo' OR ((shimmering_jin_0.open_minded_punkerslut_9 != X'6361707469766174696e675f686f6f6473346a757374696365'))) OR ((shimmering_jin_0.knowledgeable_radioazionecroatia_10 < 'agAMZlDgjAwNEPSsda' AND (shimmering_jin_0.polite_kay_5 != 1194042421446631165 AND (shimmering_jin_0.passionate_meydan_1 > 'fearlfGIIBGRHqu'))))) OR ((shimmering_jin_0.passionate_meydan_1 > 'fearless_cuLMVd' OR (shimmering_jin_0.charming_dragon_7 > 8937925428.719553)))); -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=SELECT * FROM shimmering_jin_0 WHERE (((shimmering_jin_0.passionate_meydan_1 != 'relaxed_kamo' OR ((shimmering_jin_0.open_minded_punkerslut_9 != X'6361707469766174696e675f686f6f6473346a757374696365'))) OR ((shimmering_jin_0.knowledgeable_radioazionecroatia_10 < 'agAMZlDgjAwNEPSsda' AND (shimmering_jin_0.polite_kay_5 != 1194042421446631165 AND (shimmering_jin_0.passionate_meydan_1 > 'fearlfGIIBGRHqu'))))) OR ((shimmering_jin_0.passionate_meydan_1 > 'fearless_cuLMVd' OR (shimmering_jin_0.charming_dragon_7 > 8937925428.719553)))); -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=-- ASSERT row [["'fearless_bombas'", "-5817786983.247339", "'awesome_khayati'", "'devoted_george'", "1194042421446631165", "X'72656C617865645F7A696C656C69'", "5398476000.087622", "X'666169746866756C5F6D696E7969'", "X'73696E636572655F6275726E73'", "'affectionate_bacca'"]] should be found in table shimmering_jin_0, interactive=false commit=false, rollback=false;; -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=-- ASSERT row [["'fearless_bombas'", "-5817786983.247339", "'awesome_khayati'", "'devoted_george'", "1194042421446631165", "X'72656C617865645F7A696C656C69'", "5398476000.087622", "X'666169746866756C5F6D696E7969'", "X'73696E636572655F6275726E73'", "'affectionate_bacca'"]] should be found in table shimmering_jin_0, interactive=false commit=false, rollback=false;; -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=8 interaction=UPDATE shimmering_jin_0 SET ample_weinstein_6 = X'70726F706974696F75735F6D697365696E', fantastic_cusicanqui_3 = 'sleek_hern', knowledgeable_radioazionecroatia_10 = 'proficient_urdanibia' WHERE (shimmering_jin_0.ample_weinstein_6 < X'72656c617865645f79a5b3e88c6e'AND NOT 1194042421446631165 AND NOT 'awesome_khayati'); -- 8}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=8 interaction=UPDATE shimmering_jin_0 SET ample_weinstein_6 = X'70726F706974696F75735F6D697365696E', fantastic_cusicanqui_3 = 'sleek_hern', knowledgeable_radioazionecroatia_10 = 'proficient_urdanibia' WHERE (shimmering_jin_0.ample_weinstein_6 < X'72656c617865645f79a5b3e88c6e'AND NOT 1194042421446631165 AND NOT 'awesome_khayati'); -- 8}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=-- ASSUME table shimmering_jin_0 exists; -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=-- ASSUME table shimmering_jin_0 exists; -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=INSERT INTO shimmering_jin_0 VALUES ('breathtaking_veith', -5647305430.733143, 'resourceful_melis', 'patient_yvetot', -8461818118427480898, X'73696E636572655F626F74', -3596772810.1749725, X'706F6C6974655F676F6477696E', X'696D6167696E61746976655F6D6172656368616C', 'stunning_contrepoints'), ('personable_bones', -3962999326.5573835, 'creative_canenero', 'imaginative_winn', -3003909934078792261, X'636F6E666964656E745F667265656D616E', -240558985.1604519, X'6B6E6F776C6564676561626C655F6472657A65', X'706572666563745F6D6172696E636561', 'efficient_glitterbomb'), ('competitive_feldmann', -5216131569.983045, 'magnificent_bellemare', 'blithesome_ghazzawi', 160623572937961166, X'7175616C69666965645F776F6F6473', -5027298756.763474, X'67656E65726F75735F6B6172616D757374616661', X'6D6972746866756C5F6C6175666572', 'dazzling_frank'), ('qualified_hamilton', -3996547015.694167, 'propitious_gorrion', 'productive_sparrow', 4210416603586987865, X'696E6372656469626C655F636C6172616D756E74', -6823417465.498829, X'6272696C6C69616E745F6974616C69616E61', X'676976696E675F636F76656C6C69', 'ravishing_mason'); -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=INSERT INTO shimmering_jin_0 VALUES ('breathtaking_veith', -5647305430.733143, 'resourceful_melis', 'patient_yvetot', -8461818118427480898, X'73696E636572655F626F74', -3596772810.1749725, X'706F6C6974655F676F6477696E', X'696D6167696E61746976655F6D6172656368616C', 'stunning_contrepoints'), ('personable_bones', -3962999326.5573835, 'creative_canenero', 'imaginative_winn', -3003909934078792261, X'636F6E666964656E745F667265656D616E', -240558985.1604519, X'6B6E6F776C6564676561626C655F6472657A65', X'706572666563745F6D6172696E636561', 'efficient_glitterbomb'), ('competitive_feldmann', -5216131569.983045, 'magnificent_bellemare', 'blithesome_ghazzawi', 160623572937961166, X'7175616C69666965645F776F6F6473', -5027298756.763474, X'67656E65726F75735F6B6172616D757374616661', X'6D6972746866756C5F6C6175666572', 'dazzling_frank'), ('qualified_hamilton', -3996547015.694167, 'propitious_gorrion', 'productive_sparrow', 4210416603586987865, X'696E6372656469626C655F636C6172616D756E74', -6823417465.498829, X'6272696C6C69616E745F6974616C69616E61', X'676976696E675F636F76656C6C69', 'ravishing_mason'); -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=CREATE INDEX idx_shimmering_jin_0_excellen ON shimmering_jin_0 (charming_dragon_7 DESC, relaxed_bowlegs_4 ASC); -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=CREATE INDEX idx_shimmering_jin_0_excellen ON shimmering_jin_0 (charming_dragon_7 DESC, relaxed_bowlegs_4 ASC); -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=SELECT * FROM shimmering_jin_0 WHERE (((((((shimmering_jin_0.passionate_meydan_1 != 'dazzling_jay' OR (FALSE)) OR ((shimmering_jin_0.polite_kay_5 > -2074070411704783689))) AND ((shimmering_jin_0.charming_dragon_7 != -6823417465.498829 OR (TRUE)))) AND ((shimmering_jin_0.open_minded_punkerslut_9 != X'676976696e675f636f76656c6c69'OR (shimmering_jin_0.vivacious_blat_2 < 7679974707.030196)))) OR (FALSE)) OR (TRUE)) AND ((shimmering_jin_0.fantastic_cusicanqui_3 = 'propitious_gorrion'))); -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=SELECT * FROM shimmering_jin_0 WHERE (((((((shimmering_jin_0.passionate_meydan_1 != 'dazzling_jay' OR (FALSE)) OR ((shimmering_jin_0.polite_kay_5 > -2074070411704783689))) AND ((shimmering_jin_0.charming_dragon_7 != -6823417465.498829 OR (TRUE)))) AND ((shimmering_jin_0.open_minded_punkerslut_9 != X'676976696e675f636f76656c6c69'OR (shimmering_jin_0.vivacious_blat_2 < 7679974707.030196)))) OR (FALSE)) OR (TRUE)) AND ((shimmering_jin_0.fantastic_cusicanqui_3 = 'propitious_gorrion'))); -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=9 interaction=-- ASSERT row [["'qualified_hamilton'", "-3996547015.694167", "'propitious_gorrion'", "'productive_sparrow'", "4210416603586987865", "X'696E6372656469626C655F636C6172616D756E74'", "-6823417465.498829", "X'6272696C6C69616E745F6974616C69616E61'", "X'676976696E675F636F76656C6C69'", "'ravishing_mason'"]] should be found in table shimmering_jin_0, interactive=false commit=false, rollback=false;; -- 9}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=9 interaction=-- ASSERT row [["'qualified_hamilton'", "-3996547015.694167", "'propitious_gorrion'", "'productive_sparrow'", "4210416603586987865", "X'696E6372656469626C655F636C6172616D756E74'", "-6823417465.498829", "X'6272696C6C69616E745F6974616C69616E61'", "X'676976696E675F636F76656C6C69'", "'ravishing_mason'"]] should be found in table shimmering_jin_0, interactive=false commit=false, rollback=false;; -- 9}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=2 interaction=INSERT INTO shimmering_jin_0 SELECT * FROM shimmering_jin_0 WHERE (shimmering_jin_0.knowledgeable_radioazionecroatia_10 = 'affectionate_bacca' OR shimmering_jin_0.knowledgeable_radioazionecroatia_10 > 'affectionauxDWmCWE' OR NOT 1194042421446631165); -- 2}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=2 interaction=INSERT INTO shimmering_jin_0 SELECT * FROM shimmering_jin_0 WHERE (shimmering_jin_0.knowledgeable_radioazionecroatia_10 = 'affectionate_bacca' OR shimmering_jin_0.knowledgeable_radioazionecroatia_10 > 'affectionauxDWmCWE' OR NOT 1194042421446631165); -- 2}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=5 interaction=-- ASSUME table shimmering_jin_0 exists; -- 5}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=5 interaction=-- ASSUME table shimmering_jin_0 exists; -- 5}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=5 interaction=INSERT INTO shimmering_jin_0 VALUES ('energetic_blank', -1937344547.5359173, 'confident_cores', 'unique_aps', -9130791336565023828, X'6465766F7465645F62756C6761726961', -3797811501.8984985, X'676C65616D696E675F66696C69707069', X'706C75636B795F6C696E6767', 'open_minded_iii'), ('honest_crone', -3754794056.6540565, 'insightful_jayadev', 'elegant_everett', 2866321393409459687, X'6D61676E69666963656E745F6A656E6B696E73', 1851135874.2323837, X'676C6F77696E675F706C616E636865', X'64796E616D69635F6568726C696368', 'efficient_jaimes'), ('determined_vq', 1001523306.4108925, 'dazzling_zamora', 'humorous_macsaorsa', 7703548835751668500, X'68617264776F726B696E675F636174', 2141294878.798563, X'726573706F6E7369626C655F6A757374696365', X'666561726C6573735F636C697665', 'adaptable_mag'), ('unique_communiste', -348509827.81110764, 'optimistic_tadano', 'super_front', -7236436708518353216, X'6661766F7261626C655F676F6E7A616C6F', -7835116266.481275, X'6B696E645F72656767696F', X'616666656374696F6E6174655F7269636861726473', 'relaxed_lynteris'); -- 5}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=5 interaction=INSERT INTO shimmering_jin_0 VALUES ('energetic_blank', -1937344547.5359173, 'confident_cores', 'unique_aps', -9130791336565023828, X'6465766F7465645F62756C6761726961', -3797811501.8984985, X'676C65616D696E675F66696C69707069', X'706C75636B795F6C696E6767', 'open_minded_iii'), ('honest_crone', -3754794056.6540565, 'insightful_jayadev', 'elegant_everett', 2866321393409459687, X'6D61676E69666963656E745F6A656E6B696E73', 1851135874.2323837, X'676C6F77696E675F706C616E636865', X'64796E616D69635F6568726C696368', 'efficient_jaimes'), ('determined_vq', 1001523306.4108925, 'dazzling_zamora', 'humorous_macsaorsa', 7703548835751668500, X'68617264776F726B696E675F636174', 2141294878.798563, X'726573706F6E7369626C655F6A757374696365', X'666561726C6573735F636C697665', 'adaptable_mag'), ('unique_communiste', -348509827.81110764, 'optimistic_tadano', 'super_front', -7236436708518353216, X'6661766F7261626C655F676F6E7A616C6F', -7835116266.481275, X'6B696E645F72656767696F', X'616666656374696F6E6174655F7269636861726473', 'relaxed_lynteris'); -- 5}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=5 interaction=SELECT * FROM shimmering_jin_0 WHERE (((((shimmering_jin_0.upbeat_critchley_8 = X'726573706f6e7369626c655f6a757374696365'OR ((shimmering_jin_0.knowledgeable_radioazionecroatia_10 > 'aenjvICcEZJcS' OR (shimmering_jin_0.polite_kay_5 < 8958132860241472031)))) AND ((shimmering_jin_0.knowledgeable_radioazionecroatia_10 < 'adaptabmSIXHQ'))) OR ((shimmering_jin_0.upbeat_critchley_8 != X'726573706f6e7369626c655f6a757374696365'))) OR (FALSE)) OR ((shimmering_jin_0.passionate_meydan_1 < 'determinecgiI' OR (shimmering_jin_0.ample_weinstein_6 < X'68617264776e8914ec51784c1c2ea8'OR (shimmering_jin_0.ample_weinstein_6 < X'68617264776f726b696e675f636267'))))); -- 5}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=5 interaction=SELECT * FROM shimmering_jin_0 WHERE (((((shimmering_jin_0.upbeat_critchley_8 = X'726573706f6e7369626c655f6a757374696365'OR ((shimmering_jin_0.knowledgeable_radioazionecroatia_10 > 'aenjvICcEZJcS' OR (shimmering_jin_0.polite_kay_5 < 8958132860241472031)))) AND ((shimmering_jin_0.knowledgeable_radioazionecroatia_10 < 'adaptabmSIXHQ'))) OR ((shimmering_jin_0.upbeat_critchley_8 != X'726573706f6e7369626c655f6a757374696365'))) OR (FALSE)) OR ((shimmering_jin_0.passionate_meydan_1 < 'determinecgiI' OR (shimmering_jin_0.ample_weinstein_6 < X'68617264776e8914ec51784c1c2ea8'OR (shimmering_jin_0.ample_weinstein_6 < X'68617264776f726b696e675f636267'))))); -- 5}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=5 interaction=-- ASSERT row [["'determined_vq'", "1001523306.4108925", "'dazzling_zamora'", "'humorous_macsaorsa'", "7703548835751668500", "X'68617264776F726B696E675F636174'", "2141294878.798563", "X'726573706F6E7369626C655F6A757374696365'", "X'666561726C6573735F636C697665'", "'adaptable_mag'"]] should be found in table shimmering_jin_0, interactive=false commit=false, rollback=false;; -- 5}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=5 interaction=-- ASSERT row [["'determined_vq'", "1001523306.4108925", "'dazzling_zamora'", "'humorous_macsaorsa'", "7703548835751668500", "X'68617264776F726B696E675F636174'", "2141294878.798563", "X'726573706F6E7369626C655F6A757374696365'", "X'666561726C6573735F636C697665'", "'adaptable_mag'"]] should be found in table shimmering_jin_0, interactive=false commit=false, rollback=false;; -- 5}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=1 interaction=BEGIN ; -- 1}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=1 interaction=BEGIN ; -- 1}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=1 interaction=UPDATE shimmering_jin_0 SET upbeat_critchley_8 = X'6465766F7465645F7368617069726F', ample_weinstein_6 = X'6D6972746866756C5F6775696C6C6F6E' WHERE (shimmering_jin_0.fantastic_cusicanqui_3 > 'confideoZxwyhKQ' AND shimmering_jin_0.ample_weinstein_6 < X'6465766f7465645f62756b457bb06c87'AND shimmering_jin_0.charming_dragon_7 = -3797811501.8984985); -- 1}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=1 interaction=UPDATE shimmering_jin_0 SET upbeat_critchley_8 = X'6465766F7465645F7368617069726F', ample_weinstein_6 = X'6D6972746866756C5F6775696C6C6F6E' WHERE (shimmering_jin_0.fantastic_cusicanqui_3 > 'confideoZxwyhKQ' AND shimmering_jin_0.ample_weinstein_6 < X'6465766f7465645f62756b457bb06c87'AND shimmering_jin_0.charming_dragon_7 = -3797811501.8984985); -- 1}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=1 interaction=ROLLBACK; -- 1}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=1 interaction=ROLLBACK; -- 1}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=7 interaction=INSERT INTO shimmering_jin_0 SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM shimmering_jin_0 WHERE (shimmering_jin_0.relaxed_bowlegs_4 < 'humorous_nHyUcRedm' AND NOT 1001523306.4108925 AND NOT 'dazzling_zamora')) WHERE TRUE) WHERE TRUE) WHERE TRUE; -- 7}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=7 interaction=INSERT INTO shimmering_jin_0 SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM shimmering_jin_0 WHERE (shimmering_jin_0.relaxed_bowlegs_4 < 'humorous_nHyUcRedm' AND NOT 1001523306.4108925 AND NOT 'dazzling_zamora')) WHERE TRUE) WHERE TRUE) WHERE TRUE; -- 7}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=8 interaction=DROP INDEX idx_shimmering_jin_0_excellen; -- 8}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=8 interaction=DROP INDEX idx_shimmering_jin_0_excellen; -- 8}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=6 interaction=CREATE TABLE brave_tymowski_40 (powerful_flood_41 REAL, humorous_davis_42 BLOB, diplomatic_hs_43 REAL, gregarious_bridget_44 BLOB, romantic_wildroots_45 REAL, lustrous_devaldes_46 INTEGER, charming_hewittwhite_47 INTEGER, diligent_watanabe_48 INTEGER, wondrous_volonta_49 TEXT, amazing_gavroche_50 REAL, honest_keating_51 INTEGER, passionate_chodorkoff_52 BLOB, powerful_commune_53 TEXT, shining_cairncross_54 REAL, dynamic_library_55 REAL, flexible_mtt_56 TEXT, shimmering_hayssen_57 INTEGER, breathtaking_lynteris_58 INTEGER, competitive_larsen_59 TEXT, nice_furies_60 INTEGER, open_minded_spronsen_61 TEXT, remarkable_chuang_62 INTEGER, sleek_wolman_63 BLOB, awesome_comrades_64 REAL, dynamic_josh_65 INTEGER, technological_cairns_66 BLOB, spectacular_menuck_67 TEXT, agreeable_sarnoff_68 BLOB, zestful_presley_69 INTEGER, honest_res_70 TEXT, loyal_autogestionario_71 BLOB, powerful_daizen_72 REAL, patient_odoteo_73 BLOB, vivid_szetao_74 INTEGER, hilarious_gardell_75 BLOB, splendid_canenero_76 REAL, glimmering_rafael_77 REAL, hardworking_kursions_78 TEXT, focused_sanger_79 TEXT, bright_slade_80 INTEGER, elegant_various_81 BLOB, hilarious_maxwell_82 REAL, engaging_bomb_83 INTEGER, frank_bellegarrigue_84 TEXT, powerful_hunt_85 REAL, brave_friedlaender_86 BLOB, plucky_abbott_87 BLOB, friendly_gleeson_88 BLOB, elegant_fleischmann_89 TEXT, warmhearted_acott_90 TEXT, engrossing_awry_91 TEXT, knowledgeable_hern_92 TEXT, shimmering_monroe_93 BLOB, spellbinding_kuhn_94 REAL, glimmering_knudson_95 INTEGER, upbeat_198183_96 BLOB, spellbinding_sharkey_97 BLOB, resourceful_berger_98 TEXT, stunning_thornley_99 BLOB, approachable_coombs_100 INTEGER, bright_zola_101 TEXT, upbeat_nefac_102 BLOB, insightful_puydt_103 INTEGER, captivating_bassan_104 REAL, plucky_daou_105 REAL, humorous_knudson_106 INTEGER, ambitious_alinevich_107 TEXT, glimmering_hooghan_108 BLOB, favorable_daou_109 BLOB, captivating_okeefe_110 TEXT, splendid_berkman_111 REAL, confident_rocha_112 INTEGER, ambitious_carolyn_113 TEXT, competitive_damier_114 INTEGER, upbeat_willis_115 INTEGER, unique_dunois_116 INTEGER, capable_oxalis_117 INTEGER, affectionate_sail_118 BLOB, open_minded_paredes_119 TEXT, gorgeous_hapgood_120 BLOB, unique_withdrawn_121 INTEGER, friendly_may_122 TEXT, blithesome_gurvitch_123 REAL, agreeable_taharouri_124 REAL, romantic_lynteris_125 REAL, perfect_karnage_126 REAL, thoughtful_fernandez_127 BLOB, energetic_marincea_128 BLOB, splendid_nitti_129 TEXT, sleek_malato_130 INTEGER, proficient_battistutta_131 INTEGER, ambitious_boole_132 INTEGER, bountiful_conner_133 BLOB, enchanting_monadists_134 REAL, efficient_amalgam_135 REAL, gleaming_desolationpomo_136 REAL, vibrant_ellington_137 TEXT, adept_aversion_138 BLOB, friendly_oneal_139 INTEGER); -- 6}: limbo_sim::runner::execution: 175: 
 INFO execute_interaction_rusqlite{conn_index=6 interaction=CREATE TABLE brave_tymowski_40 (powerful_flood_41 REAL, humorous_davis_42 BLOB, diplomatic_hs_43 REAL, gregarious_bridget_44 BLOB, romantic_wildroots_45 REAL, lustrous_devaldes_46 INTEGER, charming_hewittwhite_47 INTEGER, diligent_watanabe_48 INTEGER, wondrous_volonta_49 TEXT, amazing_gavroche_50 REAL, honest_keating_51 INTEGER, passionate_chodorkoff_52 BLOB, powerful_commune_53 TEXT, shining_cairncross_54 REAL, dynamic_library_55 REAL, flexible_mtt_56 TEXT, shimmering_hayssen_57 INTEGER, breathtaking_lynteris_58 INTEGER, competitive_larsen_59 TEXT, nice_furies_60 INTEGER, open_minded_spronsen_61 TEXT, remarkable_chuang_62 INTEGER, sleek_wolman_63 BLOB, awesome_comrades_64 REAL, dynamic_josh_65 INTEGER, technological_cairns_66 BLOB, spectacular_menuck_67 TEXT, agreeable_sarnoff_68 BLOB, zestful_presley_69 INTEGER, honest_res_70 TEXT, loyal_autogestionario_71 BLOB, powerful_daizen_72 REAL, patient_odoteo_73 BLOB, vivid_szetao_74 INTEGER, hilarious_gardell_75 BLOB, splendid_canenero_76 REAL, glimmering_rafael_77 REAL, hardworking_kursions_78 TEXT, focused_sanger_79 TEXT, bright_slade_80 INTEGER, elegant_various_81 BLOB, hilarious_maxwell_82 REAL, engaging_bomb_83 INTEGER, frank_bellegarrigue_84 TEXT, powerful_hunt_85 REAL, brave_friedlaender_86 BLOB, plucky_abbott_87 BLOB, friendly_gleeson_88 BLOB, elegant_fleischmann_89 TEXT, warmhearted_acott_90 TEXT, engrossing_awry_91 TEXT, knowledgeable_hern_92 TEXT, shimmering_monroe_93 BLOB, spellbinding_kuhn_94 REAL, glimmering_knudson_95 INTEGER, upbeat_198183_96 BLOB, spellbinding_sharkey_97 BLOB, resourceful_berger_98 TEXT, stunning_thornley_99 BLOB, approachable_coombs_100 INTEGER, bright_zola_101 TEXT, upbeat_nefac_102 BLOB, insightful_puydt_103 INTEGER, captivating_bassan_104 REAL, plucky_daou_105 REAL, humorous_knudson_106 INTEGER, ambitious_alinevich_107 TEXT, glimmering_hooghan_108 BLOB, favorable_daou_109 BLOB, captivating_okeefe_110 TEXT, splendid_berkman_111 REAL, confident_rocha_112 INTEGER, ambitious_carolyn_113 TEXT, competitive_damier_114 INTEGER, upbeat_willis_115 INTEGER, unique_dunois_116 INTEGER, capable_oxalis_117 INTEGER, affectionate_sail_118 BLOB, open_minded_paredes_119 TEXT, gorgeous_hapgood_120 BLOB, unique_withdrawn_121 INTEGER, friendly_may_122 TEXT, blithesome_gurvitch_123 REAL, agreeable_taharouri_124 REAL, romantic_lynteris_125 REAL, perfect_karnage_126 REAL, thoughtful_fernandez_127 BLOB, energetic_marincea_128 BLOB, splendid_nitti_129 TEXT, sleek_malato_130 INTEGER, proficient_battistutta_131 INTEGER, ambitious_boole_132 INTEGER, bountiful_conner_133 BLOB, enchanting_monadists_134 REAL, efficient_amalgam_135 REAL, gleaming_desolationpomo_136 REAL, vibrant_ellington_137 TEXT, adept_aversion_138 BLOB, friendly_oneal_139 INTEGER); -- 6}: limbo_sim::runner::execution: 292: 
 INFO execute_interaction_turso{conn_index=7 interaction=INSERT INTO shimmering_jin_0 VALUES ('independent_anarchblr', 5635451876.977125, 'bountiful_reid', 'energetic_sakolsky', 6235019744686517096, X'6C6F76656C795F726175746961696E656E', -2787488113.6448784, X'676C6F77696E675F666F72756D', X'64696C6967656E745F77756C6C7363686C65676572', 'glimmering_rafael'), ('romantic_whiteman', -8472345027.844481, 'honest_highleyman', 'dazzling_carbure', -8922675116441989462, X'76697669645F7365656C79', -6611612674.958635, X'73696E636572655F636F6575726465726F79', X'616D6961626C655F6D656E7375656C', 'mirthful_almani'), ('stunning_rothstein', 4125408025.4355774, 'marvelous_bekken', 'spectacular_trotter', -5640640777418417331, X'73747570656E646F75735F676F7269', -4149244062.3519316, X'7265736F7572636566756C5F636573617265', X'726176697368696E675F746F6E69', 'considerate_antonioli'), ('hilarious_sysyn', -2888060109.532322, 'twinkling_chanial', 'creative_missen', 5537247069266857509, X'666561726C6573735F746164646569', 9014249760.986664, X'617070726F61636861626C655F626F6F7468', X'686F6E6573745F617267656E7469', 'enchanting_hancox'), ('enchanting_federations', 7248904032.684135, 'focused_rasp', 'gorgeous_nanitcha', -2828737788863822968, X'676C65616D696E675F726F62626965', -1399111944.947195, X'656C6567616E745F686F736B696E73', X'756E697175655F617A65657A', 'gleaming_caldwell'), ('hardworking_rudnik', 9910560491.06652, 'hardworking_collaboration', 'twinkling_azeez', -8082252309231194698, X'73757065725F6672796572', 5079750148.955204, X'66756E6E795F617A61726F76', X'737061726B6C696E675F776172', 'amazing_carasso'), ('charming_tsovma', 694041980.2364597, 'knowledgeable_valls', 'nice_boggs', 7097104946076910330, X'6D6972746866756C5F646F6872696E67', 8812935014.812065, X'6672616E6B5F66726965646C61656E646572', X'706572666563745F6D6F677574696E', 'super_azurki'); -- 7}: limbo_sim::runner::execution: 175: 
 ```

### PR DESCRIPTION
**Pull request by jussisaurio**
## Closes

Closes #4033 
Closes #4125

## Bugfix number 1

When reading from sorted chunk files during external merge sort, if a chunk needed async IO to read more data, the `next_chunk_idx` (index of the chunk that caused the IO) was lost after yielding. This caused rows to be permanently dropped from the result set because `push_to_chunk_heap` didn't end up getting called again after the IO was complete.

Fix:

- track the chunk index of `pending_completion` to ensure `push_to_chunk_heap()` gets called after the IO completes.

## Bugfix number 2

When the sorter's internal read buffer was full and a prefetch read was issued, the read would request 0 bytes. This obviously returned 0 bytes read, and was incorrectly interpreted as EOF, causing the sorter to think the chunk
was exhausted when most data remained unread. This resulted in "Corrupt database: Incomplete record" errors.

Fix:

- Avoid issuing pointless 0 byte reads
- Distinguish between "no room in buffer" and "nothing left to read",
  and only the latter causes EOF
  
## Other stuff

- I added more documentation to the sorter module

## AI disclosure

I gave Opus 4.5 the failing seed from #4125 and told it that `sorter.rs` loses rows probably during spilling. It found the first bug fairly quickly and then I iterated the solution with it a bit to arrive at the final result.

I had actually given Opus 4.5 the seed of the first bug without the `--memory-io` flag, and after the first fix I noticed the seed was still failing with `--memory-io` enabled (which introduces artificial IO latency). I pointed this out to the AI and it also found the second bug very quickly, and I only participated in cleaning up the solution to make the fix minimal.

### CODE REVIEW

**Comment by jussisaurio** [comment]
Simulator InsertHeavy timed out on the PR, but I believe that just Happens Sometimes ™️ even on main

File: core/vdbe/sorter.rs [hunk 1]
```diff
@@ -277,24 +279,38 @@ impl Sorter {
...
+                // IO not complete - put it back and yield
+                self.pending_completion = Some((completion.clone(), chunk_idx));
+                return Ok(IOResult::IO(IOCompletions::Single(completion)));
             }
-            return Ok(IOResult::IO(IOCompletions::Single(group.build())));
+            // IO completed - push result to heap and retry
+            if let Some(c) = self.push_to_chunk_heap(chunk_idx)? {
+                self.pending_completion = Some((c, chunk_idx));
+            }
+            return self.next_from_chunk_heap();
```
Comment (sivukhin) [inline core/vdbe/sorter.rs]: Should we replace this tail recursion call with a loop?
