### PR TITLE
Fix panic on duplicate ORDER BY expressions with GROUP BY

### LINKED ISSUE #5227: Panic on Duplicate ORDER BY Expressions with GROUP BY
## Description
A query with GROUP BY and duplicate expressions in ORDER BY triggers an assertion failure in the optimizer.

## Reproducer
```sql
CREATE TABLE t(a);
SELECT a FROM t GROUP BY a ORDER BY a, a;
```

## Panic Message
```
thread 'main' panicked at core/translate/optimizer/order.rs:132:13:
assertion failed: group_by.exprs.len() >= order_by.len()
```

`core/translate/optimizer/order.rs:132` - `group_by_contains_all` uses `.all()` + `.any()` which allows the same GROUP BY expression to satisfy multiple ORDER BY duplicates, but the assertion assumes ORDER BY can't be longer than GROUP BY after deduplication.

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by jussisaurio**
Deduplicate ORDER BY expressions before comparing against GROUP BY in the optimizer. Duplicate ORDER BY expressions are semantically redundant and caused a false assertion failure when ORDER BY had more entries than GROUP BY (e.g. `ORDER BY a, a` with `GROUP BY a`).

Closes #5227

### CODE REVIEW

File: core/translate/select.rs [hunk 1]
```diff
@@ -489,6 +489,19 @@ fn prepare_one_select_plan(
...
+            let mut i = 0;
+            while i < key.len() {
+                if key[..i]
+                    .iter()
+                    .any(|(prev, _)| exprs_are_equivalent(prev, &key[i].0))
+                {
+                    key.remove(i);
+                } else {
+                    i += 1;
+                }
```
Comment (pedrocarlo) [inline core/translate/select.rs:503]: this loop is kind of confusing IMO, can't we use retain for this?

Comment (pedrocarlo) [reply core/translate/select.rs:503]: actually I am stupid, you need to peek at the next elements so you can't use retain
