### PR TITLE
fix: fsync DB file before truncating WAL after checkpoint

### LINKED ISSUE #4467: we should fsync(db) before truncating wal.
i wanted to understand the issue in https://github.com/tursodatabase/turso/issues/4455, so while trying to understand checkpointing i ran into this.

refer - https://gist.github.com/Pavan-Nambi/ddd182080e68f0c853efa00bbd939318

i think this should be

```zsh
pwrite64(3, "SQLite format 3\0\20\0\2\2\0@  \0\0\0\1\0\0\0\2"..., 8192, 0) = 8192
fsync(3) -- we not dng this
ftruncate(4)
```

i'm working on this to add this to simulator.  as this could be problematic  if we crash..  in middle in theory.

sqlite seems to have some crash-tests in tcl. - maybe that would be easier.

### LINKED ISSUE #4652: DB file should be fsynced BEFORE WAL is truncated in checkpoint, not AFTER

### PR DESCRIPTION
**Pull request by jussisaurio**
Closes #4467
Closes #4652

### CODE REVIEW

**Comment by jussisaurio** [comment]
@claude review this. focus on correctness, not nits

**Comment by jussisaurio** [comment]
@penberg critical fix

File: core/mvcc/database/checkpoint_state_machine.rs [hunk 1]
```diff
@@ -1074,6 +1080,59 @@ impl<Clock: LogicalClock> CheckpointStateMachine<Clock> {
...
+                if checkpoint_result.num_backfilled == 0 {
+                    self.state = CheckpointState::TruncateWal;
+                    return Ok(TransitionResult::Continue);
+                }
+
+                // Check if we already sent the sync
+                if checkpoint_result.db_sync_sent {
+                    self.state = CheckpointState::TruncateWal;
+                    return Ok(TransitionResult::Continue);
+                }
```
Comment (avinassh) [inline core/mvcc/database/checkpoint_state_machine.rs:1115]: I am trying to understand this, once sync request is sent, this state machine is invoked only after completion right? 

IOW I am wondering if this scenario is possible: 

1. We sent the sync request and set `db_sync_sent`
2. The state machine is invoked again, but `db_sync_sent` is true, so we move to `TruncateWal`
3. WAL is truncated 
4. Fsync of DB is now complete

**Review by avinassh — APPROVED** [review]

File: core/mvcc/database/checkpoint_state_machine.rs (hunk 1 above)
Comment (jussisaurio) [reply core/mvcc/database/checkpoint_state_machine.rs:1115]: After `db_sync_sent` we return `TransitionResult::Io` so this state machine won't be invoked until the IO completes, at which point we will see that `checkpoint_result.db_sync_sent` is true and move to `TruncateWal` - IOW, fsync related IO is always complete at this point

Comment (avinassh) [reply core/mvcc/database/checkpoint_state_machine.rs:1115]: may be a good idea to assert it is true in`TruncateWal` and set it to False, because DB fsync would be done by this time.

Comment (jussisaurio) [reply core/mvcc/database/checkpoint_state_machine.rs:1115]: not a bad idea per se, but that would require adding separate `sync_mode` property to that state variant just to assert it

Comment (jussisaurio) [reply core/mvcc/database/checkpoint_state_machine.rs:1115]: I added asserts about being in truncate mode to the regular checkpoint path though.

**Comment by penberg** [comment]
@jussisaurio I backported this to 0.4
