### PR TITLE
fix: ALTER TABLE RENAME COLUMN Does Not Update Partial Index WHERE Clauses

### LINKED ISSUE #5432: ALTER TABLE RENAME COLUMN Does Not Update Partial Index WHERE Clauses
## Description
`ALTER TABLE RENAME COLUMN` rewrites column names in index column lists but does not rewrite column references in partial index WHERE clauses. After renaming, the stale column reference causes either a panic (on DELETE) or silent index corruption (on UPDATE).

## Reproducer

Panic on DELETE:
```sql
CREATE TABLE t ( a, b );
CREATE INDEX idx ON t ( b ) WHERE a = 1;
ALTER TABLE t RENAME COLUMN a TO a2;
DELETE FROM t;
```

## Panic Message
```
thread 'main' panicked at core/translate/emitter.rs:1923:22:
where clause to exist
```

Silent corruption on UPDATE:
```sql
CREATE TABLE t ( a, b );
INSERT INTO t VALUES (1, 'x'), (2, 'y');
CREATE INDEX idx ON t ( b ) WHERE a = 1;
ALTER TABLE t RENAME COLUMN a TO a2;
UPDATE t SET a2 = 2;
PRAGMA integrity_check;
-- Turso: wrong # of entries in index idx, row 2 missing from index idx
-- SQLite: ok (RENAME correctly updates the WHERE clause)
```

Per [SQLite documentation](https://sqlite.org/lang_altertable.html): "The column name is changed both within the table definition itself and also within all indexes, triggers, and views that reference the column."

`core/vdbe/execute.rs:6014-6054` (on-disk SQL rewrite), `core/vdbe/execute.rs:10671-10682` (in-memory AST) - Column references in partial index WHERE clauses are not rewritten during RENAME COLUMN.

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by jussisaurio**
Rewrite column references in partial index WHERE clauses during ALTER TABLE RENAME COLUMN, both in the on-disk SQL stored in sqlite_schema and in the in-memory Index.where_clause AST.

Closes #5432

### CODE REVIEW

File: core/vdbe/execute.rs [hunk 1]
```diff
@@ -6202,6 +6202,14 @@ pub fn op_function(
                                     }
                                 }
 
+                                if let Some(ref mut wc) = where_clause {
+                                    rewrite_check_expr_column_refs(
```
Comment (jussisaurio) [inline core/vdbe/execute.rs]: this function should be renamed if it's used here too.
