### PR TITLE
Fix error handling when binding column references while translating the UPDATE statement

### LINKED ISSUE #1968: `No such column` error in update
```sql
CREATE TABLE t0 (c0 INT);
UPDATE t0 SET c0 = 1, c0 = c1;
```

The statement above produces the following error in SQLite3 but no in Turso.

```txt
Parse error: no such column: c1
  UPDATE t0 SET c0 = 1, c0 = c1;
               error here ---^
```

### PR DESCRIPTION
**Pull request by izeigerman**
Closes #1968

### CODE REVIEW

File: core/translate/update.rs [hunk 1]
```diff
@@ -155,10 +155,10 @@ pub fn prepare_update_plan(
     for set in &mut body.sets {
         let ident = normalize_ident(set.col_names[0].as_str());
         let Some(col_index) = column_lookup.get(&ident) else {
-            bail_parse_error!("Parse error: no such column: {}", ident);
+            bail_parse_error!("no such column: {}", ident);
         };
 
-        let _ = bind_column_references(&mut set.expr, &mut table_references, None);
+        bind_column_references(&mut set.expr, &mut table_references, None)?;
```
Comment (izeigerman) [inline core/translate/update.rs]: This was the root cause of the issue

**Comment by izeigerman** [comment]
@Shourya742 yes, I also noticed that the lack of span is consistent across all parsing errors. So I agree it deserves to be addressed separately.
