### PR TITLE
bindings/python: Start transaction implicitly in execute()

### LINKED ISSUE #2002: Python binding transaction handling is incorrect
We never start an interactive transaction on connection open, which results in first rollback not working correctly.

To fix this, we need to call `BEGIN` in connection init like SQLite does:

https://github.com/python/cpython/blob/main/Modules/_sqlite/connection.c#L230

SQLite:

```
>>> import sqlite3
>>> conn = sqlite3.connect('test.db')
>>> cur = conn.cursor()
>>> cur.execute("INSERT INTO t VALUES (1)")
<sqlite3.Cursor object at 0x100d2d240>
>>> conn.rollback()
>>>
(.venv) penberg@vonneumann python % sqlite3 test.db
SQLite version 3.49.1 2025-02-18 13:38:58
Enter ".help" for usage hints.
sqlite> SELECT * FROM t;
sqlite>
```

Turso:

```
>>> import turso
>>> conn = turso.connect('test.db')
>>> cur = conn.cursor()
>>> cur.execute("INSERT INTO t VALUES (1)")
<builtins.Cursor object at 0x104d8ab30>
>>> conn.rollback()
>>>
(.venv) penberg@vonneumann python % sqlite3 test.db
SQLite version 3.49.1 2025-02-18 13:38:58
Enter ".help" for usage hints.
sqlite> .schema
CREATE TABLE t (x);
sqlite> SELECT * FROM t;
1
sqlite>
```

### PR DESCRIPTION
**Pull request by penberg**
We need to start transaction implicitly in execute() for DML statements to make sure first transaction is actually started.

Fixes #2002

### CODE REVIEW

File: bindings/python/src/lib.rs [hunk 1]
```diff
@@ -93,6 +93,15 @@ impl Cursor {
             Ok::<(), anyhow::Error>(())
         })?;
 
+        if stmt_is_dml && self.conn.conn.get_auto_commit() {
```
Comment (jussisaurio) [inline bindings/python/src/lib.rs:96]: `!`missing from `self.conn.conn.get_auto_commit()`?

Comment (penberg) [reply bindings/python/src/lib.rs:96]: @jussisaurio No, we start a transaction _if_ we're not in a transaction ("autocommit mode").

Comment (jussisaurio) [reply bindings/python/src/lib.rs:96]: oh ok, so the default behavior in python sql clients is to implicitly start an interactive tx? i did not know that. i don't think e.g. any postgres clients do similarly (although i have no idea if they do in python land)

**Review by jussisaurio — APPROVED** [review]

File: bindings/python/src/lib.rs (hunk 1 above)
Comment (penberg) [reply bindings/python/src/lib.rs:96]: @jussisaurio The Python SQLite semantics are really weird. There's indeed an implicit interactive TX, except for DML statements, which are always committed :-/
