### PR TITLE
Fix seek not applying correct affinity to seek expr

### LINKED ISSUE #3707: Incorrect type conversion before comparison when using an index
From the SQLite [documentation](https://sqlite.org/datatype3.html#type_conversions_prior_to_comparison):

> If one operand has INTEGER, REAL or NUMERIC affinity and the other operand has TEXT or BLOB or no affinity then NUMERIC affinity is applied to the other operand. 

```
turso> create table t(a text);
turso> insert into t values ('10'), ('2'), ('02'), ('2a');
turso> select * from t where a >= 2;
┌────┐
│ a  │
├────┤
│ 2  │
├────┤
│ 2a │
└────┘
turso> create index idx on t(a);
turso> select * from t where a >= 2;
┌────┐
│ a  │
├────┤
│ 02 │
├────┤
│ 10 │
├────┤
│ 2  │
├────┤
│ 2a │
└────┘

```

### PR DESCRIPTION
**Pull request by pedrocarlo**
Depends on #3923 .

To have similar semantics to how `op_compare` works, we need to apply an affinity to the values referenced in the `SeekKey` that is used for seeking. This means keeping some affinity metadata for the `WhereTerms` in the optimization phase, then before seeking, we emit an affinity conversion.  Had to dig deep in the sqlite code to understand this better.

Unfortunately, we cannot have just one compare function to rule them all here, as we have a specialized/optimized compare code to handle records that have not yet been deserialized.

Closes #3707

### CODE REVIEW

File: core/translate/main_loop.rs [hunk 1]
```diff
@@ -1376,14 +1377,23 @@ fn emit_seek(
...
-            .collect(),
-    });
+            .collect();
+        if affinities.chars().any(|c| c != affinity::SQLITE_AFF_NONE) {
+            program.emit_insn(Insn::Affinity {
+                start_reg,
+                count: std::num::NonZeroUsize::new(num_regs).unwrap(),
+                affinities: seek_def
+                    .iter_affinity(&seek_def.start)
+                    .map(|affinity| affinity.aff_mask())
```
Comment (jussisaurio) [inline core/translate/main_loop.rs:1391]: `affinities` should be used here instead of calculating again?
