### PR TITLE
Fix: Evaluating expression in LIMIT and OFFSET clauses.

### LINKED ISSUE #3687: Compat: Using NULL in LIMIT clause does not throw error
SQLITE throws error when using NULL in LIMIT clause. But we dont.

Image

### PR DESCRIPTION
**Pull request by rajajisai**
Closes #3687 .

Previously, the `try_fold_expr_to_i64` function casted `NULL` as `0` when evaluating expressions in `LIMIT` or `OFFSET` clauses. I removed this function since evaluating the expression directly and relying on the MustBeInt operation for casting seems to handle everything.

### CODE REVIEW

**Comment by rajajisai** [comment]
cc: @Shourya742 . Tagging you since you implemented this part.

File: core/translate/compound_select.rs [hunk 1]
```diff
@@ -43,34 +42,46 @@ pub fn emit_program_for_compound_select(
...
+                if let Ok(value) = n.parse::<i64>() {
+                    program.add_comment(program.offset(), "LIMIT counter");
+                    program.emit_insn(Insn::Integer { value, dest: reg });
+                } else {
+                    let value = n.parse::<f64>().unwrap();
+                    program.emit_insn(Insn::Real { value, dest: reg });
+                    program.add_comment(program.offset(), "LIMIT counter");
+                    program.emit_insn(Insn::MustBeInt { reg });
+                }
+            }
```
Comment (bit-aloo) [inline core/translate/compound_select.rs]: This logic we are repeating quite often, we can put this inside a common method.

File: core/translate/emitter.rs [hunk 2]
```diff
@@ -1964,52 +1963,72 @@ fn init_limit(
...
+                        let value = n.parse::<f64>().unwrap();
+                        program.emit_insn(Insn::Real {
+                            value,
+                            dest: limit_ctx.reg_limit,
+                        });
+                        program.emit_insn(Insn::MustBeInt {
+                            reg: limit_ctx.reg_limit,
+                        });
+                    }
+                }
```
Comment (bit-aloo) [inline core/translate/emitter.rs:2016]: nstead of using unwrap, we should propagate an error in case the Numeric value fails to parse otherwise, it will cause a panic.

**Comment by rajajisai** [comment]
Sorry I got busy . Thanks @jussisaurio @Shourya742 !!
