### PR TITLE
core: Fix reprepare to properly reset statement cursors and registers

### LINKED ISSUE #3002: Panic `Option::unwrap()` on a `None` value under Whopper
```
SEED=1129049187403980750 ./whopper/bin/run --mode chaos
```

```
penberg@turing:~/src/tursodatabase/turso$ SEED=1129049187403980750 RUST_LOG=turso_whopper=trace ./whopper/bin/run --mode chaos
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
mode = chaos
seed = 1129049187403980750
TRACE turso_whopper: 112: CREATE TABLE table_0 (id INTEGER,col_1 REAL,col_2 INTEGER,col_3 REAL,col_4 TEXT,col_5 REAL,col_6 TEXT)
TRACE turso_whopper: 119: CREATE INDEX idx_table_0_0 ON table_0 (col_4 ASC)
TRACE turso_whopper: 119: CREATE INDEX idx_table_0_1 ON table_0 (id DESC)
TRACE turso_whopper: 119: CREATE INDEX idx_table_0_2 ON table_0 (col_5 DESC)
       .             I/U/D/C
TRACE turso_whopper: 367: 2 BEGIN
TRACE turso_whopper: 367: 0 BEGIN
TRACE turso_whopper: 367: 1 BEGIN
TRACE turso_whopper: 429: 2 DELETE: DELETE FROM table_0 WHERE (TRUE)
TRACE turso_whopper: 460: 0 COMMIT
TRACE turso_whopper: 417: 1 UPDATE: UPDATE table_0 SET col_5 = -2926216022.864461, col_1 = 1136343846.3760414, col_2 = 1260332354248861058, col_6 = 'breathtaking_wallace', col_3 = -8354252674.968108, id = -2763965266862900284 WHERE (TRUE)
TRACE turso_whopper: 460: 2 COMMIT
TRACE turso_whopper: 367: 2 BEGIN
TRACE turso_whopper: 367: 3 BEGIN
TRACE turso_whopper: 405: 2 INSERT: INSERT INTO table_0 VALUES (3433031730186055493, -9049649117.499245, 377748201198469116, -303828055.307354, 'hardworking_pinotnoir', 3130880977.346573, 'dazzling_identity'), (4047491512698975530, -6415241771.805258, 8252804953477887816, 6468710871.6649, 'diplomatic_karamazov', 590358226.8343716, 'hilarious_strasbourg'), (2865599543545078376, 84894401.22016525, 9113810426850381627, -1136160051.7521439, 'funny_benton', 9522389352.598354, 'magnificent_french'), (-157899885850804353, -303833796.57147026, 486259919370287064, -9427424128.005714, 'considerate_diamant', -3105334243.936157, 'kind_walker'), (8502247374804763489, -2126532888.2616653, 5690470012873526939, 4011656749.2326107, 'kind_ladrido', 1381034902.7760563, 'humorous_crane'), (2487742055507017334, -5830452441.986847, 3661939929057695925, -6299976423.211256, 'adaptable_raevsky', -7871748970.666381, 'technological_bataille'), (-5348095239593101865, -998225440.4524403, 5195262288395229508, -8305444803.975374, 'upbeat_courtney', -3943473497.4281626, 'imaginative_arrigoni'), (-6470080787150464674, -5833281407.383408, 5877012236478010308, 3023123550.254177, 'fearless_cairo', -141073531.91679573, 'generous_university')
TRACE turso_whopper: 405: 3 INSERT: INSERT INTO table_0 VALUES (-7468459471409934075, 8179435779.870651, -7868006515434924912, -5415470506.527203, 'affectionate_n1x', -88866295.57206345, 'agreeable_treloar'), (3000445982321368777, 3099814982.0727863, -5101787605795972474, -925278326.7265358, 'giving_individualiste', -6553332857.366568, 'brave_patrizia'), (406163996859206098, -3340292138.289094, -5058217201699339610, 2605267874.8582096, 'fabulous_burnett', -4601912326.914466, 'super_jedi'), (6398781934600428549, -6770226564.882048, -2332649333251794167, 6904161964.055864, 'shining_sergent', -4779129294.073781, 'hardworking_beggar'), (1530150677936272307, -8683321096.443897, -2211014401610293017, 2417417840.8996468, 'magnificent_datacide', -2218929107.793541, 'ravishing_nw'), (8028216547992752413, -8876487798.088352, 8974386493479719872, -6723037189.199554, 'glimmering_murray', -1973499548.0633707, 'spectacular_fitzpatrick')
TRACE turso_whopper: 439: 1 CREATE INDEX: CREATE INDEX idx_table_0_persiste ON table_0 (col_2 ASC, col_6 ASC, col_3 ASC)
TRACE turso_whopper: 367: 0 BEGIN
TRACE turso_whopper: 460: 1 COMMIT
TRACE turso_whopper: 417: 0 UPDATE: UPDATE table_0 SET col_3 = 7634893024.5729065, col_6 = 'glimmering_besnard', col_1 = 9240915430.267292, col_4 = 'efficient_mekan' WHERE (TRUE)

thread 'main' panicked at core/vdbe/execute.rs:6357:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55b621dc6522 - std::backtrace_rs::backtrace::libunwind::trace::h74680e970b6e0712
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x55b621dc6522 - std::backtrace_rs::backtrace::trace_unsynchronized::ha3bf590e3565a312
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x55b621dc6522 - std::sys::backtrace::_print_fmt::hcf16024cbdd6c458
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
   3:     0x55b621dc6522 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h46a716bba2450163
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
   4:     0x55b621de9153 - core::fmt::rt::Argument::fmt::ha695e732309707b7
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
   5:     0x55b621de9153 - core::fmt::write::h275e5980d7008551
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
   6:     0x55b621dc39e3 - std::io::default_write_fmt::hdc4119be3eb77042
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
   7:     0x55b621dc39e3 - std::io::Write::write_fmt::h561a66a0340b6995
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
   8:     0x55b621dc6372 - std::sys::backtrace::BacktraceLock::print::hafb9d5969adc39a0
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
   9:     0x55b621dc7932 - std::panicking::default_hook::{{closure}}::hae2e97a5c4b2b777
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
  10:     0x55b621dc7735 - std::panicking::default_hook::h3db1b505cfc4eb79
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
  11:     0x55b621dc82d2 - std::panicking::rust_panic_with_hook::h409da73ddef13937
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
  12:     0x55b621dc8046 - std::panicking::begin_panic_handler::{{closure}}::h159b61b27f96a9c2
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:699:13
  13:     0x55b621dc6a19 - std::sys::backtrace::__rust_end_short_backtrace::h5b56844d75e766fc
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
  14:     0x55b621dc7d0d - __rustc[4794b31dd7191200]::rust_begin_unwind
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
  15:     0x55b620db1480 - core::panicking::panic_fmt::hc8737e8cca20a7c8
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
  16:     0x55b620db150c - core::panicking::panic::h4a11c031239f36a8
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:145:5
  17:     0x55b620db13f9 - core::option::unwrap_failed::h62317944fa5dc382
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/option.rs:2040:5
  18:     0x55b621780f22 - core::option::Option<T>::unwrap::h9075554c2a8eda76
                               at /home/penberg/.rustup/toolchains/1.88.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1003:21
  19:     0x55b621780f22 - turso_core::vdbe::execute::op_open_write::h59d67484fde73095
                               at /home/penberg/src/tursodatabase/turso/core/vdbe/execute.rs:6355:9
  20:     0x55b620f580c3 - turso_core::vdbe::Program::step::hd8c2e1e3a0bf96c1
                               at /home/penberg/src/tursodatabase/turso/core/vdbe/mod.rs:508:19
  21:     0x55b6211c9ab0 - turso_core::Statement::step::h6e57b4930b202cb9
                               at /home/penberg/src/tursodatabase/turso/core/lib.rs:2134:23
  22:     0x55b620e05b8a - turso_whopper::perform_work::h88d915da926d3e13
                               at /home/penberg/src/tursodatabase/turso/whopper/main.rs:305:19
  23:     0x55b620e033f0 - turso_whopper::main::h47a84802078db00d
                               at /home/penberg/src/tursodatabase/turso/whopper/main.rs:172:9
  24:     0x55b620db9a4b - core::ops::function::FnOnce::call_once::hbce670d3519dd771
                               at /home/penberg/.rustup/toolchains/1.88.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  25:     0x55b620db3b0d - std::sys::backtrace::__rust_begin_short_backtrace::h2988ed03521477f3
                               at /home/penberg/.rustup/toolchains/1.88.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  26:     0x55b620ded851 - std::rt::lang_start::{{closure}}::h0a63d9613fee047c
                               at /home/penberg/.rustup/toolchains/1.88.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:199:18
  27:     0x55b621dbcfe4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb4b7cf0559a1a53b
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:284:13
  28:     0x55b621dbcfe4 - std::panicking::try::do_call::h8e6004e979ada7de
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
  29:     0x55b621dbcfe4 - std::panicking::try::hc44a0c902e55fa8c
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
  30:     0x55b621dbcfe4 - std::panic::catch_unwind::h6a5f1ccd4faaed9e
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
  31:     0x55b621dbcfe4 - std::rt::lang_start_internal::{{closure}}::h40fd26f9e7cfe6a7
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:168:24
  32:     0x55b621dbcfe4 - std::panicking::try::do_call::h047dd894cf3f6fd1
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:589:40
  33:     0x55b621dbcfe4 - std::panicking::try::h921841e1eaed56ce
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:552:19
  34:     0x55b621dbcfe4 - std::panic::catch_unwind::h108064a50ee785ec
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panic.rs:359:14
  35:     0x55b621dbcfe4 - std::rt::lang_start_internal::ha8ef919ae4984948
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/rt.rs:164:5
  36:     0x55b620ded837 - std::rt::lang_start::h80fa8ce54bd351ee
                               at /home/penberg/.rustup/toolchains/1.88.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:198:5
  37:     0x55b620e0cd2e - main
  38:     0x7fe4b2174575 - __libc_start_call_main
  39:     0x7fe4b2174628 - __libc_start_main_alias_2
  40:     0x55b620db1fa5 - <T as compact_str::traits::ToCompactString>::try_to_compact_string::h4ebdb3aac7d701f3
                               at /home/penberg/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/compact_str-0.8.1/src/traits.rs:92:20
  41:                0x0 - <unknown>

real	0m0.147s
user	0m0.102s
sys	0m0.044s
```

### PR DESCRIPTION
**Pull request by pedrocarlo**
Before we were not updating the number of registers and cursors, which meant that on a schema change the Program could now open an additional cursor and we would not have space for it in the ProgramState, which lead to the panic.

Closes #3002

### CODE REVIEW

File: core/lib.rs [hunk 1]
```diff
@@ -2305,6 +2311,14 @@ impl Statement {
...
         self.program.explain()
     }
+
+    pub fn get_sql(&self) -> &str {
+        &self.program.sql
+    }
+
+    pub fn is_done(&self) -> bool {
+        self.done
+    }
```
Comment (penberg) [inline core/lib.rs:2353]: You should invert this to `is_busy()` so we can later implement the C API https://sqlite.org/c3ref/stmt_busy.html

**Comment by penberg** [comment]
Hey @pedrocarlo, please edit out .gitignore and the log file from the commits

File: core/lib.rs [hunk 2]
```diff
@@ -2219,7 +2225,8 @@ impl Statement {
         };
         // Save parameters before they are reset
         let parameters = std::mem::take(&mut self.state.parameters);
-        self.reset();
+        self.state =
+            vdbe::ProgramState::new(self.program.max_registers, self.program.cursor_ref.len());
```
Comment (TcMits) [inline core/lib.rs]: we need to check query_mode here to know how many registers needed

Comment (TcMits) [reply core/lib.rs]: and why dont we check new max_registers/cursors then reallocate the vec, its will be cheaper

Comment (pedrocarlo) [reply core/lib.rs]: > we need to check query_mode here to know how many registers needed

For this I just copied the line that is on the `Statement::new`, so maybe it is wrong there? But I dont think so right, because the program is the that takes the QueryMode and determines the amount of registers and cursors right?

> and why dont we check new max_registers/cursors then reallocate the vec, its will be cheaper

We can, but my concern was just that we can introduce new changes in the future, and we forget to modify the `reset()` function to account for this. We actually were not reseting the internal state machines until this PR, so it is very easy to forget. The creation of a new state will most likely always be up to date. But I can of course do that is @penberg thinks its a must.

Comment (penberg) [reply core/lib.rs]: @pedrocarlo it's worth optimizing reset() because it ends up being a significant cost with prepared statements

Comment (TcMits) [reply core/lib.rs]: translate do take query_mode but it does not use it for calculating max_registers.

Comment (TcMits) [reply core/lib.rs]: query_mode is used in step function to tell program should return instructions or normal rows

Comment (TcMits) [reply core/lib.rs]: i think reset function of ProgramState should take 2 args new_max_register, new_max_cursors.

File: core/lib.rs [hunk 3]
```diff
@@ -2320,11 +2327,20 @@ impl Statement {
...
     pub fn row(&self) -> Option<&Row> {
         self.state.result_row.as_ref()
     }
+
+    pub fn get_sql(&self) -> &str {
+        &self.program.sql
+    }
+
+    pub fn is_done(&self) -> bool {
+        self.busy
```
Comment (jussisaurio) [inline core/lib.rs:2352]: how does `busy=true` imply `is_done`? this deserves a comment

Comment (pedrocarlo) [reply core/lib.rs:2352]: It does not of course, I am just stupid and forgot to rename is_done to is_busy

File: core/lib.rs (hunk 2 above)
Comment (pedrocarlo) [reply core/lib.rs]: @TcMits and @penberg, I changed it. Now it resizes the underlying vecs instead of creating a new ProgramState

Comment (TcMits) [reply core/lib.rs]: you forgot to check query_mode, i guest maybe your local branch is not the latest

https://github.com/tursodatabase/turso/blob/main/core/lib.rs#L2091-L2098

Comment (pedrocarlo) [reply core/lib.rs]: 🤦‍♂️ . Yes I will correct it in a bit
