### PR TITLE
btree: fix interior cell replacement in btrees with depth >=3

### LINKED ISSUE #2106: Simulator - Error: failed with error: 'corrupted database, stack is bigger than expected'
cargo run --bin limbo_sim -- --seed 14051286987788724219 --maximum-tests 500 
(working only in https://github.com/tursodatabase/turso/pull/2049)

commit id: 86b1b0d00976175a37e274e17828cf8c6d67e293
seed: 14051286987788724219
Error: failed with error: 'corrupted database, stack is bigger than expected'

Use `./target/debug/tursodb < shrunk.sql --experimental-indexes` to reproduce.
[shrunk.txt](https://github.com/user-attachments/files/21246801/shrunk.txt)

### PR DESCRIPTION
**Pull request by jussisaurio**
## Background

When a divider cell is deleted from an index interior page, the following algorithm is used:

1. Find predecessor: Move to largest key in left subtree of the current page. This is always a leaf page.
2. Create replacement: Convert this predecessor leaf cell to interior cell format, using original cell's left child page pointer
3. Replace: Drop original cell from parent page, insert replacement at same position
4. Cleanup: Delete the taken predecessor cell from the leaf page

Screenshot 2025-07-16 at 10 39 18

## The faulty code leading to the bug

The error in our logic was that we always expected to only traverse down one level of the btree:

```rust
let parent_page = self.stack.parent_page().unwrap();
let leaf_page = self.stack.top();
```

This meant that when the deletion happened on say, level 1, and the replacement cell was taken from level 3, we actually inserted the replacement cell into level 2 instead of level 1.

## Manifestation of the bug in issue 2106

In #2106, this manifested as the following chain of pages, going from parent to children:

3 -> 111 -> 119

- Cell to be deleted was on page 3 (whose left pointer is 111)
- Going to the largest key in the left subtree meant traversing from 3 to 111 and then from 111 to 119
- a replacement cell was taken from 119
- incorrectly inserted into 111
- and its left child pointer also set as 111!
- now whenever page 111 wanted to go to its left child page, it would just traverse back to itself, eventually causing a crash because we have a hard limit of the number of pages on the page stack.

## The fix

The fix is quite trivial: store the page we are on before we start traversing down.

Closes #2106

### CODE REVIEW

File: core/storage/btree.rs [hunk 1]
```diff
@@ -4369,6 +4369,9 @@ impl BTreeCursor {
                     // 3. Delete that key from the child page.
 
                     // Step 1: Move cursor to the largest key in the left subtree.
+                    // The largest key is always in a leaf, and so this traversal may involvegoing multiple pages downwards,
+                    // so we store the page we are currently on.
+                    let parent_page = self.stack.top();
```
Comment (jussisaurio) [inline core/storage/btree.rs]: Actually, this is not re-entrant, so let me fix it to be

**Review by pereman2 — APPROVED** [review]
good catch!
