### PR TITLE
fix: u16 Overflow in page_free_array Panics on 65536-Byte Pages #5276

### LINKED ISSUE #5276: u16 Overflow in page_free_array Panics on 65536-Byte Pages
## Description
B-tree balancing panics with arithmetic overflow on 65536-byte pages when index cells are large enough that `offset + len > u16::MAX`.

## Reproducer
```sql
PRAGMA page_size = 65536;
CREATE TABLE t(a INTEGER PRIMARY KEY, b TEXT);
CREATE INDEX idx ON t(b);
INSERT INTO t VALUES (1, printf('%010000d', 1));
INSERT INTO t VALUES (2, printf('%010000d', 2));
INSERT INTO t VALUES (3, printf('%010000d', 3));
INSERT INTO t VALUES (4, printf('%010000d', 4));
INSERT INTO t VALUES (5, printf('%010000d', 5));
INSERT INTO t VALUES (6, printf('%010000d', 6));
INSERT INTO t VALUES (7, printf('%010000d', 7));
INSERT INTO t VALUES (8, printf('%010000d', 8));
INSERT INTO t VALUES (9, printf('%010000d', 9));
INSERT INTO t VALUES (10, printf('%010000d', 10));
INSERT INTO t VALUES (11, printf('%010000d', 11));
-- Turso: panics on 11th insert
-- SQLite: succeeds
```

## Panic Message
```
thread 'main' panicked at core/storage/btree.rs:6973:23:
attempt to add with overflow
```

`core/storage/btree.rs:6973` - `offset` and `len` are `u16`. On 65536-byte pages, a cell at offset ~56000 with length ~10000 causes `offset + len = 66000 > u16::MAX`, overflowing. In release mode, this wraps silently and corrupts the page freeblock list. Fix: use `u32` or `usize` for `offset`, `len`, `end`, and the `buffered_cells_offsets`/`buffered_cells_ends` arrays.

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by jussisaurio**
In page_free_array, buffered_cells_offsets/ends arrays and local offset/len/end variables were u16, causing arithmetic overflow when offset + len > u16::MAX on 65536-byte pages with large index cells.

Changed these to usize to match the types expected by free_cell_range and eliminate the overflow.

Closes #5276

### CODE REVIEW

**Comment by jussisaurio** [comment]
This is an AI-generated PR, so I manually verified that this indeed panics on main:

```sql
turso>     PRAGMA page_size = 65536;
    CREATE TABLE t(a INTEGER PRIMARY KEY, b TEXT);
    CREATE INDEX idx ON t(b);
    INSERT INTO t VALUES (1, printf('%010000d', 1));
    INSERT INTO t VALUES (2, printf('%010000d', 2));
    INSERT INTO t VALUES (3, printf('%010000d', 3));
    INSERT INTO t VALUES (4, printf('%010000d', 4));
    INSERT INTO t VALUES (5, printf('%010000d', 5));
    INSERT INTO t VALUES (6, printf('%010000d', 6));
    INSERT INTO t VALUES (7, printf('%010000d', 7));
    INSERT INTO t VALUES (8, printf('%010000d', 8));
    INSERT INTO t VALUES (9, printf('%010000d', 9));
    INSERT INTO t VALUES (10, printf('%010000d', 10));
    INSERT INTO t VALUES (11, printf('%010000d', 11));
    SELECT a FROM t ORDER BY a;

thread 'main' panicked at core/storage/btree.rs:6973:23:
attempt to add with overflow
```

File: core/storage/btree.rs [hunk 1]
```diff
@@ -7209,6 +7209,9 @@ fn free_cell_range(
 
     let mut size = len;
     let mut end = offset + len;
+    if end > usable_space {
```
Comment (jussisaurio) [inline core/storage/btree.rs:7212]: Noticed this check was too early and we had an (existing) silent corruption case for very specific inputs (`first_block == 0` AND `offset==cur_content_area`), which could write the cell content area to be beyond the page's usable space if `end > 0`.
