### PR TITLE
Preserve BLOB-vs-no-affinity semantics in comparison coercion

### LINKED ISSUE #5134: Incorrect affinity coercion in join
Turso returns 1, but SQLite returns 0.

```
CREATE TABLE a(x);
CREATE TABLE b(x TEXT);
INSERT INTO a VALUES (1);
INSERT INTO b VALUES ('1');
SELECT count(*) FROM a JOIN b ON a.x = b.x;
```

found with claude

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Description

This PR fixes incorrect affinity coercion in comparison codegen that affected join predicates.

  For `CREATE TABLE a(x);` and `CREATE TABLE b(x TEXT);`, Turso previously returned `1` for:

  ```sql
  SELECT count(*) FROM a JOIN b ON a.x = b.x;
  ```
  while SQLite returns 0.

## Motivation and context

Issue #5134 identified a SQLite compatibility bug in affinity coercion during = comparisons in joins.

Closes #5134

### CODE REVIEW

File: core/translate/expr.rs [hunk 1]
```diff
@@ -5562,27 +5562,59 @@ pub fn comparison_affinity(
...
-    if !aff.has_affinity() {
-        Affinity::Blob
-    } else {
-        aff
+/// Return whether an expression has a real affinity for comparison purposes.
+///
+/// This intentionally distinguishes BLOB-affinity expressions (which *do* have
+/// affinity in SQLite comparison rules) from expressions with no affinity
+/// (literals, most computed expressions, unresolved registers).
+pub fn expr_has_comparison_affinity(
```
Comment (jussisaurio) [inline core/translate/expr.rs]: this looks like almost a copy of `get_expr_affinity()` - is this papering over the fact that `get_expr_affinity()` is falling back to `Affinity::Blob` (with a TODO comment about it)?

Comment (jussisaurio) [reply core/translate/expr.rs]: Also, we already have `comparison_affinity()` as well

Comment (kumarUjjawal) [reply core/translate/expr.rs]: 😬
