### PR TITLE
fix RETURNING, Statement::reset() and Program::abort()

### LINKED ISSUE #4388: RETURNING clause should write everything before starting to yield rows to caller
quoting @sivukhin : "We need to change INSERT RETURNING plan and actually insert everything and commit change first and only after that start to consume returned rows from some ephemeral table (that's how SQLite do this)"

otherwise it's problematic when users step a statement that does e.g. INSERT RETURNING and then stop consuming the statement in the middle or drop it

### LINKED ISSUE #5490: last_insert_rowid() returns 1 after INSERT with RETURNING
## Description
`last_insert_rowid()` is not updated when INSERT uses RETURNING. The value is clobbered by the ephemeral table's `NewRowid` instruction, which always assigns rowid 1. Inside RETURNING expressions `last_insert_rowid()` returns the correct value, but after the statement completes it reverts to the ephemeral table's rowid.

## Reproducer
```sql
CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT);

INSERT INTO t1 VALUES(10, 'a');
SELECT last_insert_rowid();
-- Turso: 10
-- SQLite: 10

-- Inside RETURNING: correct
INSERT INTO t1 VALUES(20, 'b') RETURNING last_insert_rowid();
-- Turso: 20
-- SQLite: 20

-- After RETURNING: wrong
SELECT last_insert_rowid();
-- Turso: 1
-- SQLite: 20

INSERT INTO t1 VALUES(50, 'c') RETURNING *;
SELECT last_insert_rowid();
-- Turso: 1
-- SQLite: 50
```

Per [SQLite documentation](https://sqlite.org/c3ref/last_insert_rowid.html): "An INSERT that fails due to a constraint violation is not a successful INSERT and does not change the value returned by this routine." Since INSERT with RETURNING succeeds, `last_insert_rowid()` should reflect the real table's rowid, not the ephemeral table's.

The ephemeral table used to buffer RETURNING rows uses `NewRowid` which sets `last_insert_rowid` to 1, clobbering the real value.

---
*This issue brought to you by Mikaël and Claude Code.*

### PR DESCRIPTION
**Pull request by jussisaurio**
Closes #4388 
Closes #5490 

## Problem 1 - RETURNING implemented wrong

We were not executing RETURNING the same way as SQLite. Our way was:

```
INSERT ROW
RETURN ROW TO CALLER
INSERT ROW
RETURN ROW TO CALLER
...
COMMIT
```

SQlite does:

```
INSERT ROW
BUFFER RETURNING RESULT ROW TO TEMP TABLE
INSERT ROW
BUFFER RETURNING RESULT ROW TO TEMP TABLE
...
RETURN ROW FROM TEMP TABLE TO CALLER
RETURN ROW FROM TEMP TABLE TO CALLER
...
COMMIT
```

This is a problem because a naive implementation of our approach on `main` would result in this:

```
INSERT ROW
RETURN ROW TO CALLER
CALLER READS ROW AND DROPS/ABANDONS STATEMENT
```

Where not all INSERTs happened, so the statement would roll back. Think from user POV: you just executed `INSERT INTO ... RETURNING ...` and got a result row back, decided not to step through the rest and moved on. Now your tx is rolled back and the inserts didn't happen. Bad.

## Our current workaround on main

On main, if there is a DML operation in progress, on Statement drop, we do a best-effort synchronous completion of the entire statement so that the DML effects of the statement persist.

1. This is not what SQLite does; instead SQLite immediately calls `Halt` and commits or rollbacks based on the `rc` (result code) on the VM.
2. @pereman2 thinks our run-statement-to-completion behavior is the cause of the bug #5422 for MVCC.

## Fix

1. Align RETURNING bytecode with SQLite; buffer to temp table and return from there.
2. Set a special `has_returned_row` flag indicating that we've emitted a ResultRow to caller.
3. In `reset_internal` if there's a DML statement (`change_cnt_on`) and we've emitted a row to caller, this signifies that all the DML is done and we now invoke Halt synchronously to commit the changes. In all other cases we roll back.
4. Consistent `EXPLAIN` naming for ephemeral tables

## Problem 2 - Statement::reset() was infallible and not handling cleanup properly

`Statement::reset()` was infallible, although it can error in several points - errors were just logged. This can mask errors and also leave them unhandled, which can result in e.g. lock leaks.

## Fix

- Make `reset()` fallible; call `reset_best_effort()` from `Statement::Drop` - which does abort cleanup on panic unwind to ensure resources are released.

## Problem 3 - Program::abort() could leave subjournal in use on error

This a problem because it can cause persistent `Busy` on future connections since they can't use the subjournal for statement subtransactions.

## Fix

Capture error in `Program::abort()` and return it at the end, but release subjournal in all cases.

## Tests

- Some synchronous integration tests to verify behavior with RETURNING
- `Simulator` tests using `MemorySimIO` for fault injection, to verify that abandoning statement after seeing `StepResult::IO` rolls back unless RETURNING scanback had already started.
- `Simulator` tests to verify that `reset()` errors do not cause resource leaks (unfreed WAL locks / subjournal use) during panics or errors propagated from `reset()`

### CODE REVIEW

**Comment by LeMikaelF** [comment]
Small regression in this PR: `changes()` now counts rows in double:

```sql
CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT);

-- Without RETURNING: correct
INSERT INTO t1 VALUES(1, 'a');
SELECT changes();  -- Returns: 1 ✓

-- With RETURNING: doubled
INSERT INTO t1 VALUES(10, 'r') RETURNING *;
SELECT changes();  -- Returns: 2  (expected: 1)

INSERT INTO t1 VALUES(11, 's'), (12, 't') RETURNING *;
SELECT changes();  -- Returns: 4  (expected: 2)

UPDATE t1 SET b = 'y' WHERE a >= 10 RETURNING *;
SELECT changes();  -- Returns: 6  (expected: 3)

DELETE FROM t1 WHERE a >= 10 RETURNING *;
SELECT changes();  -- Returns: 6  (expected: 3)
```

File: core/statement.rs [hunk 1]
```diff
@@ -492,41 +508,66 @@ impl Statement {
...
+                                    self.program.abort(&self.pager, Some(&e), &mut self.state)
+                                {
+                                    tracing::error!(
+                                        "Abort failed during statement reset: {abort_err}"
+                                    );
+                                }
+                                break;
+                            }
+                        }
+                        Err(e) => {
```
Comment (LeMikaelF) [inline core/statement.rs:576]: does this mean that commits can fail silently?

File: testing/runner/tests/snapshot_tests/returning/snapshots/returning__upsert-returning.snap [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+  35  Insert          1  20   1  t2    8  intkey=r[1] data=r[20]
+  36  Copy            1  21   0        0  r[21]=r[1]
+  37  Copy           16  22   0        0  r[22]=r[16]
+  38  Copy           17  23   0        0  r[23]=r[17]
+  39  MakeRecord     21   3  24        0  r[24]=mkrec(r[21..23])
+  40  NewRowid        0  25   0        0  r[25]=rowid
+  41  Insert          0  24  25        0  intkey=r[25] data=r[24]
+  42  Goto            0  43   0        0
+  43  Goto            0  44   0        0
+  44  Rewind          0  50   0        0  Rewind  t2
```
Comment (LeMikaelF) [inline testing/runner/tests/snapshot_tests/returning/snapshots/returning__upsert-returning.snap]: bug in the comment here, this is the ephemeral table's cursor, but the comment says t2

File: core/statement.rs (hunk 1 above)
Comment (jussisaurio) [reply core/statement.rs:576]: Yeah - I made `reset()` fallible in 6847bf211d4dda1ad5de4032de66cd52fa69c3cf and added `reset_best_effort()` for Drop

**Comment by jussisaurio** [comment]
> Small regression in this PR: `changes()` now counts rows in double:
> 
> ```sql
> CREATE TABLE t1(a INTEGER PRIMARY KEY, b TEXT);
> 
> -- Without RETURNING: correct
> INSERT INTO t1 VALUES(1, 'a');
> SELECT changes();  -- Returns: 1 ✓
> 
> -- With RETURNING: doubled
> INSERT INTO t1 VALUES(10, 'r') RETURNING *;
> SELECT changes();  -- Returns: 2  (expected: 1)
> 
> INSERT INTO t1 VALUES(11, 's'), (12, 't') RETURNING *;
> SELECT changes();  -- Returns: 4  (expected: 2)
> 
> UPDATE t1 SET b = 'y' WHERE a >= 10 RETURNING *;
> SELECT changes();  -- Returns: 6  (expected: 3)
> 
> DELETE FROM t1 WHERE a >= 10 RETURNING *;
> SELECT changes();  -- Returns: 6  (expected: 3)
> ```

fixed this - ephemeral inserts for returning were not marked with the ephemeral flag. added test.

File: testing/runner/tests/snapshot_tests/returning/snapshots/returning__upsert-returning.snap (hunk 2 above)
Comment (jussisaurio) [reply testing/runner/tests/snapshot_tests/returning/snapshots/returning__upsert-returning.snap]: fixed this and made ephemeral table namings consistent in EXPLAIN

File: core/statement.rs (hunk 1 above)
Comment (jussisaurio) [reply core/statement.rs:576]: Had to amend this a bit in https://github.com/tursodatabase/turso/pull/5478/commits/98db50bf4219b65a39b505738e3d07d362bbee86 and https://github.com/tursodatabase/turso/pull/5478/commits/c0ac8bc83b63d0a5c6abe7355320527d35352bd8 to ensure resources dont leak

File: core/vdbe/explain.rs [hunk 3]
```diff
@@ -16,16 +18,46 @@ pub fn insn_to_row(
     program: &PreparedProgram,
     insn: &Insn,
 ) -> (&'static str, i64, i64, i64, Value, i64, String) {
-    let get_table_or_index_name = |cursor_id: usize| {
+    let mut ephemeral_cursors = HashSet::new();
+    let mut changed = true;
+    while changed {
```
Comment (LeMikaelF) [inline core/vdbe/explain.rs]: This can be simplified, if I understand correctly it's meant to prevent adding non-ephemeral cursors from `OpenDup` to `ephemeral_cursors`, but `OpenDup` can only ever be used with ephemeral tables, so line 38 can be done inconditionally, and the `while` loop can be removed.

File: core/statement.rs [hunk 4]
```diff
@@ -487,46 +503,143 @@ impl Statement {
...
+                            break;
+                        }
+                        Ok(vdbe::execute::InsnFunctionStepResult::IO(_)) => {
+                            if let Err(e) = self.pager.io.step() {
+                                capture_reset_error(
+                                    &mut reset_error,
+                                    e,
+                                    "Error committing during statement reset",
+                                );
+                                break;
```
Comment (LeMikaelF) [inline core/statement.rs:573]: nit: this could be simplified by breaking a `Result<()>` out of the loop (`break e`)
