### PR TITLE
Ephemeral Table in Update

### LINKED ISSUE #1713: test-constraint is flaky
eg https://github.com/tursodatabase/limbo/actions/runs/15563481054/job/43821565394?pr=1697

fails _sometimes_

### PR DESCRIPTION
**Pull request by pedrocarlo**
Closes #1713. Adds ephemeral table when a rowid_alias is being updated.

### CODE REVIEW

File: core/translate/emitter.rs [hunk 1]
```diff
@@ -860,6 +870,29 @@ fn emit_program_for_update(
         });
     }
 
+    let temp_cursor_id = {
+        // Sqlite determines we should create an ephemeral table if we do not have a FROM clause
+        // Difficult to say what items from the plan can be checked for this so currently just checking the where clause
+        // https://github.com/sqlite/sqlite/blob/master/src/update.c#L395
+        // https://github.com/sqlite/sqlite/blob/master/src/update.c#L670
```
Comment (jussisaurio) [inline core/translate/emitter.rs]: https://github.com/sqlite/sqlite/blob/master/src/update.c#L276C1-L283C42
```
/*
** Process an UPDATE statement.
**
**   UPDATE OR IGNORE tbl SET a=b, c=d FROM tbl2... WHERE e<5 AND f NOT NULL;
**          \_______/ \_/     \______/      \_____/       \________________/
**           onError   |      pChanges         |                pWhere
**                     \_______________________/
**                               pTabList
```

https://github.com/sqlite/sqlite/blob/master/src/update.c#L391C1-L395C58
```
  /* If there was a FROM clause, set nChangeFrom to the number of expressions
  ** in the change-list. Otherwise, set it to 0. There cannot be a FROM
  ** clause if this function is being called to generate code for part of
  ** an UPSERT statement.  */
  nChangeFrom = (pTabList->nSrc>1) ? pChanges->nExpr : 0;
```

https://github.com/sqlite/sqlite/blob/master/src/update.c#L670
```
if( nChangeFrom==0 && HasRowid(pTab) ){
  ...open ephemeral...
}
```

https://github.com/sqlite/sqlite/blob/792d1d1b6d61453c4c4af6813f5877818f51a13c/src/sqliteInt.h#L2537
```
/* Does the table have a rowid */
--
2537 | #define HasRowid(X)     (((X)->tabFlags & TF_WithoutRowid)==0)
```



Doesn't this mean the ephemeral index should be opened if:

1. the table _has a rowid_ (not just "rowid alias is being updated"), and
2. there is no FROM clause, OR there are no `SET` expressions -- which effectively just means "there is no FROM clause".

Currently we don't support `UPDATE ... FROM` so this just flattens to:

1. the table has a rowid

File: core/translate/emitter.rs [hunk 2]
```diff
@@ -1400,3 +1431,77 @@ fn init_limit(
...
+        root_page: 0, // Not relevant for ephemeral table definition
+        name: "ephemeral_scratch".to_string(),
+        has_rowid: true,
+        primary_key_columns: vec![],
+        columns: vec![Column {
+            name: Some("rowid".to_string()),
+            ty: Type::Integer,
+            ty_str: "INTEGER".to_string(),
+            primary_key: false,
+            is_rowid_alias: false,
```
Comment (jussisaurio) [inline core/translate/emitter.rs]: Shouldn't this be true? And `primary_key` too? and notnull?

File: core/translate/main_loop.rs [hunk 3]
```diff
@@ -376,8 +377,11 @@ pub fn open_loop(
             Operation::Scan { iter_dir, .. } => {
                 match &table.table {
                     Table::BTree(_) => {
-                        let iteration_cursor_id = index_cursor_id.unwrap_or_else(|| {
-                            table_cursor_id.expect("Either index or table cursor must be opened")
+                        let iteration_cursor_id = temp_cursor_id.unwrap_or_else(|| {
+                            index_cursor_id.unwrap_or_else(|| {
+                                table_cursor_id
+                                    .expect("Either index or table cursor must be opened")
```
Comment (jussisaurio) [inline core/translate/main_loop.rs]: this `.expect()` should be changed since it now includes 3 different possibilities

File: core/translate/main_loop.rs [hunk 4]
```diff
@@ -992,8 +997,11 @@ pub fn close_loop(
                 program.resolve_label(loop_labels.next, program.offset());
                 match &table.table {
                     Table::BTree(_) => {
-                        let iteration_cursor_id = index_cursor_id.unwrap_or_else(|| {
-                            table_cursor_id.expect("Either index or table cursor must be opened")
+                        let iteration_cursor_id = temp_cursor_id.unwrap_or_else(|| {
+                            index_cursor_id.unwrap_or_else(|| {
+                                table_cursor_id
+                                    .expect("Either index or table cursor must be opened")
```
Comment (jussisaurio) [inline core/translate/main_loop.rs]: this `.expect()` should be changed since it now includes 3 different possibilities

File: core/types.rs [hunk 5]
```diff
@@ -853,15 +853,18 @@ impl ImmutableRecord {
...
+    ) -> Self {
+        let mut values = Vec::with_capacity(len);
+        let mut serials = Vec::with_capacity(len);
         let mut size_header = 0;
         let mut size_values = 0;
 
         let mut serial_type_buf = [0; 9];
         // write serial types
-        for value in registers {
+        for value in registers.clone() {
```
Comment (jussisaurio) [inline core/types.rs]: why?

File: testing/update.test [hunk 6]
```diff
@@ -193,3 +193,10 @@ do_execsql_test_on_specific_db {:memory:} update_where_or_regression_test {
     SELECT * from t;
 } {lovely_revolt
 lovely_revolt}
+
+do_execsql_test_in_memory_any_error update_primary_key_constraint_error {
+    CREATE TABLE eye (study REAL, spring BLOB, save TEXT, thank REAL, election INTEGER, PRIMARY KEY (election));                  
+    INSERT INTO eye VALUES (183559032.521585, x'6625d092', 'Trial six should.', 2606132742.43174, 2817);
+    INSERT INTO eye VALUES (78255586.9204539, x'651061e8', 'World perhaps.', -5815764.49018679, 1917);
+    UPDATE eye SET election = 6150;
```
Comment (jussisaurio) [inline testing/update.test:222]: Does this test work differently without the changes in this PR? Also, why does this PR fix the flaky constraint test?

File: core/translate/emitter.rs (hunk 1 above)
Comment (pedrocarlo) [reply core/translate/emitter.rs]: The `nChangeFrom` is kind of misleading. I am pretty sure that it encompasses filtering expression as well and not only a `UPDATE ... FROM`. If you look below you will see that we should only use an ephemeral table when we have a rowid_alias getting updated. 

```sql
sqlite> CREATE TABLE eye (study REAL, spring BLOB, save TEXT, thank REAL, election INTEGER, PRIMARY KEY (election));
sqlite> explain UPDATE eye SET election = 6150;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     31    0                    0   Start at 31
1     Null           0     1     2                    0   r[1..2]=NULL
2     OpenEphemeral  1     0     1                    0   nColumn=0
3     OpenRead       0     2     0     0              0   root=2 iDb=0; eye
4     Rewind         0     8     0                    0
5       Rowid          0     2     0                    0   r[2]= rowid of 0
6       Insert         1     1     2                    0   intkey=r[2] data=r[1]
7     Next           0     5     0                    1
8     OpenWrite      0     2     0     5              0   root=2 iDb=0; eye
9     Rewind         1     30    0                    0
10      Rowid          1     2     0                    0   r[2]= rowid of 1
11      NotExists      0     29    2                    0   intkey=r[2]
12      Integer        6150  3     0                    0   r[3]=6150
13      MustBeInt      3     0     0                    0
14      Column         0     0     4                    0   r[4]= cursor 0 column 0
15      RealAffinity   4     0     0                    0
16      Column         0     1     5                    0   r[5]= cursor 0 column 1
17      Column         0     2     6                    0   r[6]= cursor 0 column 2
18      Column         0     3     7                    0   r[7]= cursor 0 column 3
19      RealAffinity   7     0     0                    0
20      Null           0     8     0                    0   r[8]=NULL
21      Eq             3     25    2                    144 if r[2]==r[3] goto 25
22      Noop           0     0     0                    0   uniqueness check for ROWID
23      NotExists      0     25    3                    0   intkey=r[3]
24      Halt           1555  2     0     eye.election   2
25      MakeRecord     4     5     9     EABED          0   r[9]=mkrec(r[4..8])
26      NotExists      0     29    2                    0   intkey=r[2]
27      Delete         0     4     3     eye            0
28      Insert         0     9     3     eye            5   intkey=r[3] data=r[9]
29    Next           1     10    0                    0
30    Halt           0     0     0                    0
31    Transaction    0     1     1     0              1   usesStmtJournal=1
32    Goto           0     1     0                    0
sqlite> explain UPDATE eye SET study = 6150;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     18    0                    0   Start at 18
1     Null           0     1     2                    0   r[1..2]=NULL
2     Noop           1     0     1                    0
3     OpenWrite      0     2     0     5              0   root=2 iDb=0; eye
4     Rewind         0     17    0                    0
5       Rowid          0     2     0                    0   r[2]= rowid of 0
6       IsNull         2     17    0                    0   if r[2]==NULL goto 17
7       Integer        6150  3     0                    0   r[3]=6150
8       Column         0     1     4                    0   r[4]= cursor 0 column 1
9       Column         0     2     5                    0   r[5]= cursor 0 column 2
10      Column         0     3     6                    0   r[6]= cursor 0 column 3
11      RealAffinity   6     0     0                    0
12      Null           0     7     0                    0   r[7]=NULL
13      MakeRecord     3     5     1     EABED          0   r[1]=mkrec(r[3..7])
14      Delete         0     68    2     eye            2
15      Insert         0     1     2     eye            7   intkey=r[2] data=r[1]
16    Next           0     5     0                    1
17    Halt           0     0     0                    0
18    Transaction    0     1     1     0              1   usesStmtJournal=0
19    Goto           0     1     0                    0
```

## Why do we need the ephemeral table in this case?
In the first query above, after we insert the first row to with the updated rowid, it changes the btree configuration and messes up cursor iteration. If we are not iterating on a temp table, the Next instruction will just say that there are no more records to go through and halt the program afterwards.

Comment (pedrocarlo) [reply core/translate/emitter.rs]: However from further experimentation, the way I did the Ephemeral table loop was a bit naive. As sqlite emits a different kind of ephemeral loop depending on the WHERE clause. I will revisit this PR to account for this.

```sql
sqlite> explain UPDATE eye SET election = 6150 WHERE election = 1000;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     26    0                    0   Start at 26
1     Null           0     1     2                    0   r[1..2]=NULL
2     Noop           1     0     1                    0
3     OpenWrite      0     2     0     5              0   root=2 iDb=0; eye
4     Integer        1000  9     0                    0   r[9]=1000
5     SeekRowid      0     7     9                    0   intkey=r[9]
6     Rowid          0     2     0                    0   r[2]= rowid of 0
7     IsNull         2     25    0                    0   if r[2]==NULL goto 25
8     Integer        6150  3     0                    0   r[3]=6150
9     MustBeInt      3     0     0                    0
10    Column         0     0     4                    0   r[4]= cursor 0 column 0
11    RealAffinity   4     0     0                    0
12    Column         0     1     5                    0   r[5]= cursor 0 column 1
13    Column         0     2     6                    0   r[6]= cursor 0 column 2
14    Column         0     3     7                    0   r[7]= cursor 0 column 3
15    RealAffinity   7     0     0                    0
16    Null           0     8     0                    0   r[8]=NULL
17    Eq             3     21    2                    144 if r[2]==r[3] goto 21
18    Noop           0     0     0                    0   uniqueness check for ROWID
19    NotExists      0     21    3                    0   intkey=r[3]
20    Halt           1555  2     0     eye.election   2
21    MakeRecord     4     5     1     EABED          0   r[1]=mkrec(r[4..8])
22    NotExists      0     25    2                    0   intkey=r[2]
23    Delete         0     4     3     eye            0
24    Insert         0     1     3     eye            5   intkey=r[3] data=r[1]
25    Halt           0     0     0                    0
26    Transaction    0     1     1     0              1   usesStmtJournal=0
27    Goto           0     1     0                    0
sqlite> explain UPDATE eye SET election = 6150 WHERE election > 1000;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     31    0                    0   Start at 31
1     Null           0     1     2                    0   r[1..2]=NULL
2     OpenEphemeral  1     0     1                    0   nColumn=0
3     OpenRead       0     2     0     0              0   root=2 iDb=0; eye
4     SeekGT         0     8     9                    0   key=r[9]; pk
5       Rowid          0     2     0                    0   r[2]= rowid of 0
6       Insert         1     1     2                    0   intkey=r[2] data=r[1]
7     Next           0     5     0                    0
8     OpenWrite      0     2     0     5              0   root=2 iDb=0; eye
9     Rewind         1     30    0                    0
10      Rowid          1     2     0                    0   r[2]= rowid of 1
11      NotExists      0     29    2                    0   intkey=r[2]
12      Integer        6150  3     0                    0   r[3]=6150
13      MustBeInt      3     0     0                    0
14      Column         0     0     4                    0   r[4]= cursor 0 column 0
15      RealAffinity   4     0     0                    0
16      Column         0     1     5                    0   r[5]= cursor 0 column 1
17      Column         0     2     6                    0   r[6]= cursor 0 column 2
18      Column         0     3     7                    0   r[7]= cursor 0 column 3
19      RealAffinity   7     0     0                    0
20      Null           0     8     0                    0   r[8]=NULL
21      Eq             3     25    2                    144 if r[2]==r[3] goto 25
22      Noop           0     0     0                    0   uniqueness check for ROWID
23      NotExists      0     25    3                    0   intkey=r[3]
24      Halt           1555  2     0     eye.election   2
25      MakeRecord     4     5     10    EABED          0   r[10]=mkrec(r[4..8])
26      NotExists      0     29    2                    0   intkey=r[2]
27      Delete         0     4     3     eye            0
28      Insert         0     10    3     eye            5   intkey=r[3] data=r[10]
29    Next           1     10    0                    0
30    Halt           0     0     0                    0
31    Transaction    0     1     1     0              1   usesStmtJournal=1
32    Integer        1000  9     0                    0   r[9]=1000
33    Goto           0     1     0                    0
sqlite> explain UPDATE eye SET election = 6150 WHERE election > 1000 AND study = 1;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     34    0                    0   Start at 34
1     Null           0     1     2                    0   r[1..2]=NULL
2     OpenEphemeral  1     0     1                    0   nColumn=0
3     OpenRead       0     2     0     1              0   root=2 iDb=0; eye
4     SeekGT         0     11    9                    0   key=r[9]; pk
5       Column         0     0     10                   0   r[10]= cursor 0 column 0
6       RealAffinity   10    0     0                    0
7       Ne             11    10    10    BINARY-8       85  if r[10]!=r[11] goto 10
8       Rowid          0     2     0                    0   r[2]= rowid of 0
9       Insert         1     1     2                    0   intkey=r[2] data=r[1]
10    Next           0     5     0                    0
11    OpenWrite      0     2     0     5              0   root=2 iDb=0; eye
12    Rewind         1     33    0                    0
13      Rowid          1     2     0                    0   r[2]= rowid of 1
14      NotExists      0     32    2                    0   intkey=r[2]
15      Integer        6150  3     0                    0   r[3]=6150
16      MustBeInt      3     0     0                    0
17      Column         0     0     4                    0   r[4]= cursor 0 column 0
18      RealAffinity   4     0     0                    0
19      Column         0     1     5                    0   r[5]= cursor 0 column 1
20      Column         0     2     6                    0   r[6]= cursor 0 column 2
21      Column         0     3     7                    0   r[7]= cursor 0 column 3
22      RealAffinity   7     0     0                    0
23      Null           0     8     0                    0   r[8]=NULL
24      Eq             3     28    2                    144 if r[2]==r[3] goto 28
25      Noop           0     0     0                    0   uniqueness check for ROWID
26      NotExists      0     28    3                    0   intkey=r[3]
27      Halt           1555  2     0     eye.election   2
28      MakeRecord     4     5     12    EABED          0   r[12]=mkrec(r[4..8])
29      NotExists      0     32    2                    0   intkey=r[2]
30      Delete         0     4     3     eye            0
31      Insert         0     12    3     eye            5   intkey=r[3] data=r[12]
32    Next           1     13    0                    0
33    Halt           0     0     0                    0
34    Transaction    0     1     1     0              1   usesStmtJournal=1
35    Integer        1000  9     0                    0   r[9]=1000
36    Integer        1     11    0                    0   r[11]=1
37    Goto           0     1     0                    0
sqlite> explain UPDATE eye SET election = 6150 WHERE election > 1000 AND election != 1001;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     33    0                    0   Start at 33
1     Null           0     1     2                    0   r[1..2]=NULL
2     OpenEphemeral  1     0     1                    0   nColumn=0
3     OpenRead       0     2     0     0              0   root=2 iDb=0; eye
4     SeekGT         0     10    9                    0   key=r[9]; pk
5       Rowid          0     10    0                    0   r[10]=eye.rowid
6       Eq             11    9     10                   84  if r[10]==r[11] goto 9
7       Rowid          0     2     0                    0   r[2]= rowid of 0
8       Insert         1     1     2                    0   intkey=r[2] data=r[1]
9     Next           0     5     0                    0
10    OpenWrite      0     2     0     5              0   root=2 iDb=0; eye
11    Rewind         1     32    0                    0
12      Rowid          1     2     0                    0   r[2]= rowid of 1
13      NotExists      0     31    2                    0   intkey=r[2]
14      Integer        6150  3     0                    0   r[3]=6150
15      MustBeInt      3     0     0                    0
16      Column         0     0     4                    0   r[4]= cursor 0 column 0
17      RealAffinity   4     0     0                    0
18      Column         0     1     5                    0   r[5]= cursor 0 column 1
19      Column         0     2     6                    0   r[6]= cursor 0 column 2
20      Column         0     3     7                    0   r[7]= cursor 0 column 3
21      RealAffinity   7     0     0                    0
22      Null           0     8     0                    0   r[8]=NULL
23      Eq             3     27    2                    144 if r[2]==r[3] goto 27
24      Noop           0     0     0                    0   uniqueness check for ROWID
25      NotExists      0     27    3                    0   intkey=r[3]
26      Halt           1555  2     0     eye.election   2
27      MakeRecord     4     5     12    EABED          0   r[12]=mkrec(r[4..8])
28      NotExists      0     31    2                    0   intkey=r[2]
29      Delete         0     4     3     eye            0
30      Insert         0     12    3     eye            5   intkey=r[3] data=r[12]
31    Next           1     12    0                    0
32    Halt           0     0     0                    0
33    Transaction    0     1     1     0              1   usesStmtJournal=1
34    Integer        1000  9     0                    0   r[9]=1000
35    Integer        1001  11    0                    0   r[11]=1001
36    Goto           0     1     0                    0
```

File: core/types.rs (hunk 5 above)
Comment (pedrocarlo) [reply core/types.rs]: Cloning an iterator of references is very cheap as it would be the same as iterating over references. Maybe instead of adding the `Clone` trait to the parameter, it would be better to add the `Copy` trait to the parameter to show this be more intuitive.

File: core/translate/emitter.rs (hunk 1 above)
Comment (jussisaurio) [reply core/translate/emitter.rs]: hi @pedrocarlo , looks like sqlite effectively does the same as we do with `optimize_plan()`, i.e. if there's a point query on a single rowid `SeekRowid` gets used, if it's a range query like `rowidalias > 100` then a seek ends up being used, etc. the difference is that the target ("QueryDestination") of that access on the table is then an ephemeral index, and then the ephemeral index is scanned afterwards. Would be great if that was reflected in `UpdatePlan`.

Comment (pedrocarlo) [reply core/translate/emitter.rs]: Yeah, I noticed this after I enabled the optimize table access and saw that it was doing the seeks differently depending on the query. The logic for detecting the need for an ephemeral index seems simple for now. I was doing it in the `emit_program_for_update` but this detection is better suited inside the `prepare_update_plan`

File: core/translate/emitter.rs (hunk 2 above)
Comment (pedrocarlo) [reply core/translate/emitter.rs]: Yep

**Comment by pedrocarlo** [comment]
@jussisaurio I thought this was going to be easy, it was a bit harder than I imagined... But, I think now we should be able to correctly emit the ephemeral table to filter the rowids for updating. In principle, a similar approach could be applied to Delete as well, which would probably fix the index problems we were having before.

File: core/translate/optimizer/mod.rs [hunk 7]
```diff
@@ -120,13 +120,13 @@ fn optimize_update_plan(plan: &mut UpdatePlan, _schema: &Schema) -> Result<()> {
...
     // sqlite first creates an ephemeral index to store the current values so the tree traversal
     // doesn't get messed up while updating.
-    // let _ = optimize_table_access(
-    //     &mut plan.table_references,
-    //     &schema.indexes,
-    //     &mut plan.where_clause,
-    //     &mut plan.order_by,
-    //     &mut None,
-    // )?;
+    let _ = optimize_table_access(
```
Comment (jussisaurio) [inline core/translate/optimizer/mod.rs:121]: if this is now fixed, the comment above should also be removed

**Comment by jussisaurio** [comment]
Food for thought - I wonder if this would work as a combination of `SelectPlan` and `UpdatePlan` so that existing mechanisms could be composed to implement this, instead of putting more logic into the bytecode emission modules.

```rust
// pseudocode

UpdatePlan {
  // If the table's rowid alias is used, gather all the target rowids into an ephemeral table, and then use that table as the single JoinedTable for the actual UPDATE loop.
  ephemeral_select: Option<SelectPlan>
  ...
}

// example:
SelectPlan {
    table_references: ["users"]
    result_columns: [Expr::Rowid],
    where_clause: Vec<WhereTerm>, // original WHERE terms from the UPDATE clause
    group_by: None, // N/A
    order_by: None, // N/A
    aggregates: vec![], // N/A
    limit: None, // N/A
    query_destination: QueryDestination::EphemeralIndex { cursor_id: 1, index: Arc::new(new_eph_table_lol()) }
}

// optimize this plan as normal
if let Some(ephemeral_select) = update_plan.ephemeral_select.as_mut() {
  optimize_select_plan(ephemeral_select)
} else {
  optimize_update_plan(update_plan)
}
```

Then for the actual `UpdatePlan` the only `JoinedTable` would be the ephemeral table (in fact it's unclear why `UpdatePlan` even has a vector of tables), and it would have no WHERE terms because those were used in the ephemeral select.

```rust
// pseudocode
if let Some(ephemeral_select) = update_plan.ephemeral_select.take() {
  emit_select(ephemeral_select)
}
emit_update(update_plan)
```

My (perhaps naive) idea would be that this would "just work" without a lot of `if something and something` branching inside the bytecode emission functions. The update loop would ofc need to OpenWrite the necessary cursors for deletion, however.

**Comment by pedrocarlo** [comment]
@jussisaurio I think it worked well. I moved a lot of the logic to the update plan and tried to reuse existing functions to emit the bytecode for the ephemeral table. The main difference to SQLite, is that for we emit a `IdxInsert` instead of an `Insert` due to the fact that when translating the SelectPlan it requires us to have an ephemeral Index instead of a ephemeral Table.

File: core/translate/update.rs [hunk 8]
```diff
@@ -188,13 +193,98 @@ pub fn prepare_update_plan(
...
+            ephemeral: true,
+            root_page: 0,
+            columns: vec![],
+            unique: true,
+            has_rowid: true,
+        });
+
+        let temp_cursor_id = program.alloc_cursor_id(CursorType::BTreeIndex(index.clone()));
+
+        program.emit_insn(Insn::OpenEphemeral {
```
Comment (jussisaurio) [inline core/translate/update.rs]: Allocating the cursor ID is obviously okay here, but `OpenEphemeral` should probably happen in `emitter.rs` before the `ephemeral_plan` is translated. I think mixing plan parsing and VDBE instruction emission isn't the best idea just for separation of concerns

File: core/translate/update.rs [hunk 9]
```diff
@@ -188,13 +193,98 @@ pub fn prepare_update_plan(
...
+                },
+                alias: None,
+                contains_aggregates: false,
+            }],
+            where_clause,       // original WHERE terms from the UPDATE clause
+            group_by: None,     // N/A
+            order_by: None,     // N/A
+            aggregates: vec![], // N/A
+            limit: None,        // N/A
+            query_destination: QueryDestination::EphemeralIndex {
```
Comment (jussisaurio) [inline core/translate/update.rs]: How about a new `QueryDestination::EphemeralTable` variant, so that we do the same as SQLite does?
