### PR TITLE
Get aliases to where shall they be used

### LINKED ISSUE #3678: UPDATE table alias should be visible to WHERE clause
SQLite allows the updated table to be aliased and the alias to be used in the WHERE clause:

```
sqlite> create table t(a);
sqlite> update t as tt set tt.a = 1; -- alias is not visible in SET
Parse error: near ".": syntax error
  update t as tt set tt.a = 1;
                       ^--- error here
sqlite> update t as tt set a = 1 where tt.a = 0; -- alias is visible in WHERE
```

But not Turso:

```
turso> create table t(a);
turso> update t as tt set a = 1 where tt.a = 0;
  × Parse error: no such table: tt
```

### PR DESCRIPTION
**Pull request by Pavan-Nambi**
closes #3678

### CODE REVIEW

File: core/translate/update.rs [hunk 1]
```diff
@@ -185,7 +185,11 @@ pub fn prepare_update_plan(
             Table::BTree(btree_table) => Table::BTree(btree_table.clone()),
             _ => unreachable!(),
         },
-        identifier: table_name.to_string(),
+        // get em aliases
```
Comment (jussisaurio) [inline core/translate/update.rs]: remove this comment

Comment (Pavan-Nambi) [reply core/translate/update.rs]: 😅yeah

Comment (Pavan-Nambi) [reply core/translate/update.rs]: Sorry about that i was bit too in mood xd
