### PR TITLE
Return error instead of panicing when 1. short read occurs 2. page type is invalid

### LINKED ISSUE #4501: Handle short reads gracefully instead of panicking
I am in the process of improving `PRAGMA integrity_check` and testing it with some real corrupted databases but I can't get to actually testing it because we just crash with:

```rust
Error: Exit code 101

     thread 'main' panicked at core/storage/sqlite3_ondisk.rs:545:17:
     read returned 0 bytes but empty reads are not allowed
     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In general, a corrupted database should not be a process-terminating event.

### PR DESCRIPTION
**Pull request by jussisaurio**
Closes #4501 

## Beef

Instead of panicing when we read less data than expected, return a `ShortRead` or `ShortReadWalFrame` error. Furthermore, don't panic on invalid `PageType`, return `Corrupt` instead.

The point is that we shouldn't terminate the process if we read from a corrupted database. This doesn't eliminate nearly all of those cases yet, but we should eventually eliminate them all.

## Implementation details

  - `ReadCompletion` now returns `Option<CompletionError>` and the return value of `c.complete()` is checked by the completion system in `callback()`, and if `Some`, is set into the Completion's error field.
  - New tests to verify short read errors
  - Tests run with checksum feature disabled because it interferes with verifying that we return a short read error

### CODE REVIEW

File: tests/integration/storage/short_read.rs [hunk 1]
```diff
@@ -0,0 +1,245 @@
+#[cfg(not(feature = "checksum"))]
+use crate::common::{do_flush, limbo_exec_rows_fallible, run_query, TempDatabase};
+#[cfg(not(feature = "checksum"))]
+use rand::{rng, RngCore};
+#[cfg(not(feature = "checksum"))]
+use std::fs::OpenOptions;
+
+/// Test that truncating a database file results in a ShortRead error.
+#[cfg(not(feature = "checksum"))]
```
Comment (avinassh) [inline tests/integration/storage/short_read.rs]: isn't this unnecessary when you have module level `cfg(not(...))` is set tests/integration/storage/mod.rs

Comment (jussisaurio) [reply tests/integration/storage/short_read.rs]: yeah probably 👍

Comment (avinassh) [reply tests/integration/storage/short_read.rs]: btw it is unclear to me why checksum feature interferes here, because short read error should come from IO layer and checksum verification is done after a successful read

Comment (jussisaurio) [reply tests/integration/storage/short_read.rs]: @avinassh because it panics with `page should be loaded` or something when the checksum verification fails

Comment (jussisaurio) [reply tests/integration/storage/short_read.rs]: actually the `test_corruption_turso_magic_bytes` test on `main` also panics with `page should be loaded`

**Comment by penberg** [comment]
@jussisaurio Backport to 0.4?
