### PR TITLE
Fix read_entire_wal_dumb: incrementally build the frame cache

### LINKED ISSUE #2240: File read fails if WAL or DB is really big
thread 'main' panicked at core/storage/sqlite3_ondisk.rs:1358:9:
read(2147483646) != expected(2760173432)
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: turso_core::storage::sqlite3_ondisk::read_entire_wal_dumb::{{closure}}
   3: <turso_core::io::unix::UnixFile as turso_core::io::File>::pread::{{closure}}
   4: <turso_core::io::unix::UnixFile as turso_core::io::File>::pread

Related to #1767

### PR DESCRIPTION
**Pull request by PThorpe92**
closes #2240

Incrementally build the frame cache by reading the WAL file in chunks instead of reading the entire file into memory.

image

### CODE REVIEW

File: core/storage/sqlite3_ondisk.rs [hunk 1]
```diff
@@ -1650,205 +1653,306 @@ pub fn read_entire_wal_dumb(file: &Arc<dyn File>) -> Result<Arc<RwLock<WalFileSh
...
-                        header_locked.salt_2,
-                        frame_h_salt_1,
-                        frame_h_salt_2,
-                        frame_idx
-                    );
-                    break;
-                }
+        let consumed = self.process_frames(buf_slice, &header_copy, use_native);
+        self.off_atomic.fetch_add(consumed as u64, Ordering::AcqRel);
+        // If we didn’t consume the full chunk, we hit a stop condition
```
Comment (sivukhin) [inline core/storage/sqlite3_ondisk.rs:1854]: Can it be that the reason for early stop of process_frames were partial read which was not aligned to the wal frame size boundaries?

**Review by sivukhin — APPROVED** [review]
