### PR TITLE
Fix FTS LIMIT 0/-1 handling to avoid Tantivy overflow

### LINKED ISSUE #4971: fts panics with limit -1 and limit 0
```
CREATE TABLE articles (id INTEGER PRIMARY KEY, title TEXT, body TEXT);
CREATE INDEX fts_articles ON articles USING fts (title, body);
INSERT INTO articles VALUES (1, 'hello world', 'this is a test');
SELECT fts_score(title, body, 'hello') as score FROM articles ORDER BY score DESC LIMIT -1;
```

```
thread 'main' panicked at /home/pavan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tantivy-0.25.0/src/collector/top_score_collector.rs:983:21:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    20813 IOT instruction (core dumped)  ./target/release/tursodb --experimental-index-method
```
for  `LIMIT 0`   crashes (Tantivy limit>0 panic) 

sqlite behaviour i believe is 

for limit 0 it returns nothing
for limit -1 it returns all rows.

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Description

- Treat FTS `LIMIT 0` as returning no rows without querying Tantivy.
- Treat negative FTS limits as “no limit” (uses the existing max cap), matching SQLite behavior.
- Add integration test coverage for `LIMIT 0` and `LIMIT -1`.

## Motivation and context

 `LIMIT 0` and `LIMIT -1` on FTS queries could panic inside Tantivy (`capacity overflow`). SQLite returns zero rows for `LIMIT 0` and all rows for `LIMIT -1`. This change aligns behavior and prevents the crash.

Closes #4971

## Description of AI Usage

Used for pr body

### CODE REVIEW

File: tests/integration/index_method/mod.rs [hunk 1]
```diff
@@ -709,6 +709,43 @@ fn test_fts_order_by_and_limit(tmp_db: TempDatabase) {
...
+        &conn,
+        "SELECT fts_score(title, body, 'hello') as score FROM articles ORDER BY score DESC LIMIT 0",
+    );
+    assert!(rows.is_empty());
+
+    let rows = limbo_exec_rows(
+        &conn,
+        "SELECT fts_score(title, body, 'hello') as score FROM articles ORDER BY score DESC LIMIT -1",
+    );
+    assert_eq!(rows.len(), 2);
```
Comment (jussisaurio) [inline tests/integration/index_method/mod.rs:740]: i don't know much about our FTS but why does this return 2 rows when it has no WHERE filter and there are 3 articles? by design?

Comment (kumarUjjawal) [reply tests/integration/index_method/mod.rs:740]: Yes, by design in our FTS index method. The “pattern 0” path (`SELECT fts_score(...) ORDER BY score DESC LIMIT ?`) runs a Tantivy search and only returns matching docs; it doesn’t compute scores for non‑matches. It’s effectively an implicit `WHERE fts_match(...)`, so only the 2 rows containing “hello” show up. For clarity, I can add a comment or change the test to include an explicit `WHERE fts_match(...)` if you think that would help other contributors.
